//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Owin.Hosting {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Owin.Hosting.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following errors occurred while attempting to load the app..
        /// </summary>
        internal static string Exception_AppLoadFailure {
            get {
                return ResourceManager.GetString("Exception_AppLoadFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to resolve an instance of {0} from the IServiceProvider..
        /// </summary>
        internal static string Exception_FailedToResolveService {
            get {
                return ResourceManager.GetString("Exception_FailedToResolveService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The settings file is improperly formatted. It should consist of one name=value pair per line.  Empty lines or lines beginning with &apos;#&apos; are ignored..
        /// </summary>
        internal static string Exception_ImproperlyFormattedSettingsFile {
            get {
                return ResourceManager.GetString("Exception_ImproperlyFormattedSettingsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; Create method must take two parameters..
        /// </summary>
        internal static string Exception_ServerFactoryParameterCount {
            get {
                return ResourceManager.GetString("Exception_ServerFactoryParameterCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; Create method must have a second parameter of type IDictionary&lt;string,object&gt;..
        /// </summary>
        internal static string Exception_ServerFactoryParameterType {
            get {
                return ResourceManager.GetString("Exception_ServerFactoryParameterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server factory could not be located for the given input: {0}.
        /// </summary>
        internal static string Exception_ServerNotFound {
            get {
                return ResourceManager.GetString("Exception_ServerNotFound", resourceCulture);
            }
        }
    }
}
