//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharedResourceNamespace {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LoaderResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LoaderResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Owin.Loader.LoaderResources", typeof(LoaderResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly &apos;{0}&apos; was not found for the given configuration string &apos;{1}&apos;..
        /// </summary>
        internal static string AssemblyNotFound {
            get {
                return ResourceManager.GetString("AssemblyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Assembly found for the given configuration string &apos;{0}&apos;. Expected &apos;AssemblyName.ClassName&apos;, &apos;AssemblyName.ClassName.MethodName&apos;, or &apos;Namespace.Class, AssemblyName&apos;..
        /// </summary>
        internal static string AutodetectFailed {
            get {
                return ResourceManager.GetString("AutodetectFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No class &apos;{0}&apos; was found in assembly &apos;{1}&apos; for the  given configuration string &apos;{2}&apos;..
        /// </summary>
        internal static string ClassNotFoundInAssembly {
            get {
                return ResourceManager.GetString("ClassNotFoundInAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No assembly found containing class Startup or AssemblyName.Startup..
        /// </summary>
        internal static string NoAssemblyWithStartup {
            get {
                return ResourceManager.GetString("NoAssemblyWithStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Configuration method was found in class &apos;{0}&apos;..
        /// </summary>
        internal static string NoConfigMethodInClass {
            get {
                return ResourceManager.GetString("NoConfigMethodInClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; does not define method &apos;{1}&apos;..
        /// </summary>
        internal static string TypeDoesNotHaveMethod {
            get {
                return ResourceManager.GetString("TypeDoesNotHaveMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method &apos;{2}&apos; on type &apos;{1}&apos; does not have the expected signature. Expected &apos;void {0}(IAppBuilder)&apos;, &apos;object {0}(IDictionary&lt;string, object&gt;)&apos;, or &apos;object {0}()&apos;..
        /// </summary>
        internal static string UnexpectedMethodSignature {
            get {
                return ResourceManager.GetString("UnexpectedMethodSignature", resourceCulture);
            }
        }
    }
}
