//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Owin.Security.OpenIdConnect {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Owin.Security.OpenIdConnect.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BackchannelTimeout cannot be less or equal to TimeSpan.Zero..
        /// </summary>
        internal static string ArgsException_BackchallelLessThanZero {
            get {
                return ResourceManager.GetString("ArgsException_BackchallelLessThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OIDC_20001: The query string for Logout is not a well formed URI. The runtime cannot redirect. Redirect uri: &apos;{0}&apos;..
        /// </summary>
        internal static string Exception_RedirectUri_LogoutQueryString_IsNotWellFormed {
            get {
                return ResourceManager.GetString("Exception_RedirectUri_LogoutQueryString_IsNotWellFormed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An ICertificateValidator cannot be specified at the same time as an HttpMessageHandler unless it is a An ICertificateValidator cannot be specified at the same time as an HttpMessageHandler unless it is a WebRequestHandler..
        /// </summary>
        internal static string Exception_ValidatorHandlerMismatch {
            get {
                return ResourceManager.GetString("Exception_ValidatorHandlerMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OICE_20006: The &apos;c_hash&apos; claim was not a JSON string but multivalued, jwt: &apos;{0}&quot;..
        /// </summary>
        internal static string ProtocolException_CHashClaimInJwtPayloadIsNotAString {
            get {
                return ResourceManager.GetString("ProtocolException_CHashClaimInJwtPayloadIsNotAString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OICE_20007: The &apos;c_hash&apos; claim was null or an empty string, jwt: &apos;{0}&apos;..
        /// </summary>
        internal static string ProtocolException_CHashClaimInJwtPayloadIsNullOrEmpty {
            get {
                return ResourceManager.GetString("ProtocolException_CHashClaimInJwtPayloadIsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OICE_20003: A claim of type: &apos;{0}&apos;, representing the c_hash which is required when an &apos;id_token + code&apos; is received was not found in the jwt token: &apos;{1}&apos;..
        /// </summary>
        internal static string ProtocolException_CHashClaimNotFoundInJwt {
            get {
                return ResourceManager.GetString("ProtocolException_CHashClaimNotFoundInJwt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OICE_20010: The c_hash: &apos;{0}&apos; did not validate with the code: &apos;{1}&apos;, algorithm: &apos;{2}&apos;, jwt: &apos;{3}&apos;..
        /// </summary>
        internal static string ProtocolException_CHashNotValid {
            get {
                return ResourceManager.GetString("ProtocolException_CHashNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OICE_20002: A claim of type: &apos;{0}&apos;, representing the nonce was not found in the jwt token: &apos;{1}&apos;..
        /// </summary>
        internal static string ProtocolException_NonceClaimNotFoundInJwt {
            get {
                return ResourceManager.GetString("ProtocolException_NonceClaimNotFoundInJwt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OICE_20005: The &apos;nonce&apos; found in the jwt token: &apos;{0}&apos;,  did not match the expected nonce: &apos;{1}&apos;..
        /// </summary>
        internal static string ProtocolException_NonceInJwtDoesNotMatchExpected {
            get {
                return ResourceManager.GetString("ProtocolException_NonceInJwtDoesNotMatchExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OICE_20004: A &apos;nonce&apos; was not found.  The jwt token contained this nonce: &apos;{0}&apos;..
        /// </summary>
        internal static string ProtocolException_NonceWasNotFound {
            get {
                return ResourceManager.GetString("ProtocolException_NonceWasNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OICE_20008: The algorithm: &apos;{0}&apos; specified in the jwt header was unable to create a hashAlgorithm, jwt: &apos;{1}&apos;. See inner exception for details..
        /// </summary>
        internal static string ProtocolException_UnableToCreateHashAlgorithmWhenValidatingCHash {
            get {
                return ResourceManager.GetString("ProtocolException_UnableToCreateHashAlgorithmWhenValidatingCHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OICE_20009: The algorithm: &apos;{0}&apos; specified in the jwt header resulted in a hashAlgorithm that was null,  jwt: &apos;{1}&apos;..
        /// </summary>
        internal static string ProtocolException_UnableToCreateNullHashAlgorithmWhenValidatingCHash {
            get {
                return ResourceManager.GetString("ProtocolException_UnableToCreateNullHashAlgorithmWhenValidatingCHash", resourceCulture);
            }
        }
    }
}
