jobs:
- template: /eng/common/templates/jobs/jobs.yml
  parameters:
    enableMicrobuild: true
    enablePublishBuildArtifacts: true
    enablePublishTestResults: true
    enablePublishBuildAssets: true
    enablePublishUsingPipelines: ${{ variables._PublishUsingPipelines }}
    enableTelemetry: true
    mergeTestResults: true
    jobs:
    - job: Windows
      ${{ if eq(variables['System.TeamProject'], 'public') }}:
        pool:
          name: NetCore-Svc-Public
          image: 1es-windows-2019
      variables:
      # Only enable publishing in official builds.
      - ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
        # Publish-Build-Assets provides: MaestroAccessToken, BotAccount-dotnet-maestro-bot-PAT
        - group: Publish-Build-Assets
        - name: _OfficialBuildArgs
          value: /p:DotNetSignType=$(_SignType)
                 /p:TeamName=$(_TeamName)
                 /p:DotNetPublishUsingPipelines=$(_PublishUsingPipelines)
                 /p:OfficialBuildId=$(BUILD.BUILDNUMBER)
        - name: _SignType
          value: real
      # else
      - ${{ if or(eq(variables['System.TeamProject'], 'public'), in(variables['Build.Reason'], 'PullRequest')) }}:
        - name: _OfficialBuildArgs
          value: ''
        - name: _SignType
          value: test

      steps:
      - checkout: self
        clean: true
      - script: eng\common\cibuild.cmd -configuration $(_BuildConfig) -prepareMachine $(_OfficialBuildArgs)
        displayName: Build and Publish
      - ${{ if eq(variables['System.TeamProject'], 'public') }}:
        - task: PublishBuildArtifacts@1
          displayName: Upload TestResults
          condition: always()
          continueOnError: true
          inputs:
            pathtoPublish: artifacts/TestResults/$(_BuildConfig)/
            artifactName: $(Agent.Os)_$(Agent.JobName) TestResults
            artifactType: Container
            parallel: true
        - task: PublishBuildArtifacts@1
          displayName: Upload package artifacts
          condition: and(succeeded(), eq(variables['system.pullrequest.isfork'], false), eq(variables['_BuildConfig'], 'Release'))
          inputs:
            pathtoPublish: artifacts/packages/
            artifactName: artifacts
            artifactType: Container
            parallel: true
      - ${{ if eq(variables['System.TeamProject'], 'internal') }}: 
        - task: 1ES.PublishPipelineArtifact@1
          inputs:
            path: $(Build.SourcesDirectory)/artifacts/TestResults/$(_BuildConfig)/
            artifact: drop
        - task: 1ES.PublishPipelineArtifact@1
          condition: and(succeeded(), eq(variables['system.pullrequest.isfork'], false), eq(variables['_BuildConfig'], 'Release'))
          inputs:
            path: $(Build.SourcesDirectory)/artifacts/packages
            artifact: drop

- ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
- template: eng\common\templates\post-build\post-build.yml
  parameters:
    publishingInfraVersion: 3
    # Symbol validation isn't being very reliable lately. This should be enabled back
    # once this issue is resolved: https://github.com/dotnet/arcade/issues/2871
    enableSymbolValidation: false
    # It's a private repo in github so this won't pass until we create an internal mirror
    enableSourceLinkValidation: false
    enableSigningValidation: false
    enableNugetValidation: false
    # This is to enable SDL runs part of Post-Build Validation Stage
    SDLValidationParameters:
      enable: true
      continueOnError: false
      params: ' -SourceToolsList @("policheck","credscan")
      -TsaInstanceURL $(_TsaInstanceURL)
      -TsaProjectName $(_TsaProjectName)
      -TsaNotificationEmail $(_TsaNotificationEmail)
      -TsaCodebaseAdmin $(_TsaCodebaseAdmin)
      -TsaBugAreaPath $(_TsaBugAreaPath)
      -TsaIterationPath $(_TsaIterationPath)
      -TsaRepositoryName "AspNetKatana"
      -TsaCodebaseName "AspNetKatana"
      -TsaPublish $True
      '
