//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.32559
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Owin.Diagnostics {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Owin.Diagnostics.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are seeing this page because DiagnosticsPageMiddleware was added to your web application..
        /// </summary>
        internal static string DiagnosticsPageHtml_Information {
            get {
                return ResourceManager.GetString("DiagnosticsPageHtml_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Error Message.
        /// </summary>
        internal static string DiagnosticsPageHtml_TestErrorMessage {
            get {
                return ResourceManager.GetString("DiagnosticsPageHtml_TestErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Error Page.
        /// </summary>
        internal static string DiagnosticsPageHtml_TestErrorSection {
            get {
                return ResourceManager.GetString("DiagnosticsPageHtml_TestErrorSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnostics Page.
        /// </summary>
        internal static string DiagnosticsPageHtml_Title {
            get {
                return ResourceManager.GetString("DiagnosticsPageHtml_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cookies.
        /// </summary>
        internal static string ErrorPageHtml_CookiesButton {
            get {
                return ResourceManager.GetString("ErrorPageHtml_CookiesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment.
        /// </summary>
        internal static string ErrorPageHtml_EnvironmentButton {
            get {
                return ResourceManager.GetString("ErrorPageHtml_EnvironmentButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Headers.
        /// </summary>
        internal static string ErrorPageHtml_HeadersButton {
            get {
                return ResourceManager.GetString("ErrorPageHtml_HeadersButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No cookie data..
        /// </summary>
        internal static string ErrorPageHtml_NoCookieData {
            get {
                return ResourceManager.GetString("ErrorPageHtml_NoCookieData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No header data..
        /// </summary>
        internal static string ErrorPageHtml_NoHeaderData {
            get {
                return ResourceManager.GetString("ErrorPageHtml_NoHeaderData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No QueryString data..
        /// </summary>
        internal static string ErrorPageHtml_NoQueryStringData {
            get {
                return ResourceManager.GetString("ErrorPageHtml_NoQueryStringData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query.
        /// </summary>
        internal static string ErrorPageHtml_QueryButton {
            get {
                return ResourceManager.GetString("ErrorPageHtml_QueryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stack.
        /// </summary>
        internal static string ErrorPageHtml_StackButton {
            get {
                return ResourceManager.GetString("ErrorPageHtml_StackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Server Error.
        /// </summary>
        internal static string ErrorPageHtml_Title {
            get {
                return ResourceManager.GetString("ErrorPageHtml_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown location.
        /// </summary>
        internal static string ErrorPageHtml_UnknownLocation {
            get {
                return ResourceManager.GetString("ErrorPageHtml_UnknownLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string ErrorPageHtml_ValueColumn {
            get {
                return ResourceManager.GetString("ErrorPageHtml_ValueColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable.
        /// </summary>
        internal static string ErrorPageHtml_VariableColumn {
            get {
                return ResourceManager.GetString("ErrorPageHtml_VariableColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string WelcomeHeader {
            get {
                return ResourceManager.GetString("WelcomeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more about the Microsoft OWIN components.
        /// </summary>
        internal static string WelcomeLearnMicrosoftOwin {
            get {
                return ResourceManager.GetString("WelcomeLearnMicrosoftOwin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more about OWIN.
        /// </summary>
        internal static string WelcomeLearnOwin {
            get {
                return ResourceManager.GetString("WelcomeLearnOwin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your OWIN application has been successfully started.
        /// </summary>
        internal static string WelcomeStarted {
            get {
                return ResourceManager.GetString("WelcomeStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your OWIN application has been successfully started..
        /// </summary>
        internal static string WelcomeTitle {
            get {
                return ResourceManager.GetString("WelcomeTitle", resourceCulture);
            }
        }
    }
}
