//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18207
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Owin.Diagnostics.Views {
    
    #line 1 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
    using System;
    
    #line default
    #line hidden
    
    #line 2 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
    using System.Linq;
    
    #line default
    #line hidden
    
    #line 3 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
    using Views;
    
    #line default
    #line hidden
    
    
    public class ErrorPage : Microsoft.Owin.Diagnostics.Views.BaseView {
        
#line hidden
        
        #line 5 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
 
    public Views.ErrorPageModel Model { get; set; }

        #line default
        #line hidden
        
        
        public ErrorPage() {
        }
        
        public override void Execute() {
            
            #line 8 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
  
    Response.StatusCode = 500;
    Response.ReasonPhrase = "Internal Server Error";
    Response.ContentType = "text/html";
    StackFrame first = Model.StackFrames.FirstOrDefault();
    string location = "";
    if (Model.Error.TargetSite != null && Model.Error.TargetSite.DeclaringType != null)
    {
        location = Model.Error.TargetSite.DeclaringType.FullName + "." + Model.Error.TargetSite.Name;
    }
    else if (first != null)
    {
        location = first.Function;
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n<!DOCTYPE html>\r\n\r\n<html");

WriteLiteral(" lang=\"en\"");

WriteLiteral(" xmlns=\"http://www.w3.org/1999/xhtml\"");

WriteLiteral(">\r\n    <head>\r\n        <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(" />\r\n        <title>");

            
            #line 28 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
          Write(Resources.ErrorPageHtml_Title);

            
            #line default
            #line hidden
WriteLiteral("</title>\r\n        <style>\r\n");

WriteLiteral("            ");

            
            #line 30 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
        WriteLiteral(@"body {
    font-family: 'Segoe UI',Tahoma,Arial,Helvetica,sans-serif;
    font-size: .813em;
    line-height: 1.4em;
    color: #222;
}

h1, h2, h3, h4, h5 {
    /*font-family: 'Segoe UI',Tahoma,Arial,Helvetica,sans-serif;*/
    font-weight: 100;
}

h1 {
    color: #44525e;
    margin: 15px 5px 0 0;
}

h2 {
    margin: 10px 5px 0 0;
}

h3 {
    color: #363636;
    margin: 5px 5px 0 0;
}

code {
    font-family: consolas, ""Courier New"", courier, monospace;
}

#headers {
    font-size: 18px;
    padding: 0px;
}

    #headers li {
        display: inline;
        margin: 5px;
        padding: 10px;
        color: #a0a0a0;
    }

        #headers li.selected {
            background: rgb(147, 208, 144);
            color: #fff;
        }

        #headers li:hover {
            background: #55a56b;
            color: #fff;
        }

#stackpage ul {
    list-style: none;
    padding-left: 0;
    margin: 0;
}

#stackpage .frame:hover {
    background-color: #f0f0f0;
    text-decoration: none;
}

#stackpage .frame {
    padding: 5px;
    border-bottom: 1px #ddd solid;
}

    #stackpage .frame h3 {
        padding: 5px;
        margin: 0;
    }

#stackpage .source {
    padding: 0px;
}

    #stackpage .source ol li {
        font-family: consolas, ""Courier New"", courier, monospace;
        white-space: pre;
    }

    #stackpage .source ol.highlight li {
        /*color: #e22;*/
        /*font-weight: bold;*/
    }

        #stackpage .source ol.highlight li span {
            /*color: #000;*/
        }

#stackpage .frame:hover .source ol.highlight li span {
    color: #fff;
    background: rgb(150, 58, 70);
}

#stackpage .source ol.collapsable li {
    color: #888;
}

    #stackpage .source ol.collapsable li span {
        color: #606060;
    }

.page table {
    border-collapse: separate;
    border-spacing: 0;
    margin: 0 0 20px;
}

.page th {
    vertical-align: bottom;
    padding: 10px 5px 5px 5px;
    font-weight: 400;
    color: #a0a0a0;
    text-align: left;
}

.page td {
    padding: 3px 10px;
}

.page th, .page td {
    border-right: 1px #ddd solid;
    border-bottom: 1px #ddd solid;
    border-left: 1px transparent solid;
    border-top: 1px transparent solid;
    box-sizing: border-box;
}

    .page th:last-child, .page td:last-child {
        border-right: 1px transparent solid;
    }

    .page td.length {
        text-align: right;
    }

a {
    color: #1ba1e2;
    text-decoration: none;
}

    a:hover {
        color: #13709e;
        text-decoration: underline;
    }
");

            
            #line default
            #line hidden
WriteLiteral(" \r\n        </style>\r\n    </head>\r\n    <body>\r\n                \r\n        <h1>");

            
            #line 35 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
       Write(Model.Error.GetType().Name);

            
            #line default
            #line hidden
WriteLiteral("</h1>        \r\n        <h2>");

            
            #line 36 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
       Write(Model.Error.Message);

            
            #line default
            #line hidden
WriteLiteral("</h2>        \r\n");

            
            #line 37 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
        
            
            #line default
            #line hidden
            
            #line 37 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
         if (!string.IsNullOrEmpty(location) && first != null && !string.IsNullOrEmpty(first.File))
        {

            
            #line default
            #line hidden
WriteLiteral("            <p>");

            
            #line 39 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
          Write(location);

            
            #line default
            #line hidden
WriteLiteral(" in <code");

WriteAttribute("title", Tuple.Create(" title=\"", 1163), Tuple.Create("\"", 1182)
            
            #line 39 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
, Tuple.Create(Tuple.Create("", 1171), Tuple.Create<System.Object, System.Int32>(first.File
            
            #line default
            #line hidden
, 1171), false)
);

WriteLiteral(">");

            
            #line 39 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
                                                 Write(System.IO.Path.GetFileName(first.File));

            
            #line default
            #line hidden
WriteLiteral("</code>, line ");

            
            #line 39 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
                                                                                                      Write(first.Line);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n");

            
            #line 40 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
        }
        else if (!string.IsNullOrEmpty(location))
        {

            
            #line default
            #line hidden
WriteLiteral("            <p>");

            
            #line 43 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
          Write(location);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n");

            
            #line 44 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
        }
        else
        {

            
            #line default
            #line hidden
WriteLiteral("            <p>");

            
            #line 47 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
          Write(Resources.ErrorPageHtml_UnknownLocation);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n");

            
            #line 48 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("        <ul");

WriteLiteral(" id=\"headers\"");

WriteLiteral(">\r\n            <li");

WriteLiteral(" id=\"stack\"");

WriteLiteral(" class=\"selected\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 51 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
           Write(Resources.ErrorPageHtml_StackButton);

            
            #line default
            #line hidden
WriteLiteral("\r\n            </li>\r\n            <li");

WriteLiteral(" id=\"query\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 54 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
           Write(Resources.ErrorPageHtml_QueryButton);

            
            #line default
            #line hidden
WriteLiteral("\r\n            </li>\r\n            <li");

WriteLiteral(" id=\"cookies\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 57 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
           Write(Resources.ErrorPageHtml_CookiesButton);

            
            #line default
            #line hidden
WriteLiteral("\r\n            </li>\r\n            <li");

WriteLiteral(" id=\"headers\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 60 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
           Write(Resources.ErrorPageHtml_HeadersButton);

            
            #line default
            #line hidden
WriteLiteral("\r\n            </li>\r\n            <li");

WriteLiteral(" id=\"environment\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 63 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
           Write(Resources.ErrorPageHtml_EnvironmentButton);

            
            #line default
            #line hidden
WriteLiteral("\r\n            </li>\r\n        </ul>\r\n        <div");

WriteLiteral(" id=\"stackpage\"");

WriteLiteral(" class=\"page\"");

WriteLiteral(">\r\n            <ul>\r\n");

            
            #line 68 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
                
            
            #line default
            #line hidden
            
            #line 68 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
                 foreach (var frame in Model.StackFrames)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <li");

WriteLiteral(" class=\"frame\"");

WriteLiteral(">\r\n                        <h3>");

            
            #line 71 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
                       Write(frame.Function);

            
            #line default
            #line hidden
WriteLiteral(" in <code");

WriteAttribute("title", Tuple.Create(" title=\"", 2285), Tuple.Create("\"", 2304)
            
            #line 71 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
, Tuple.Create(Tuple.Create("", 2293), Tuple.Create<System.Object, System.Int32>(frame.File
            
            #line default
            #line hidden
, 2293), false)
);

WriteLiteral(">");

            
            #line 71 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
                                                                    Write(System.IO.Path.GetFileName(frame.File));

            
            #line default
            #line hidden
WriteLiteral("</code></h3>\r\n\r\n");

            
            #line 73 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 73 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
                         if (frame.Line != 0 && frame.ContextCode != null)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <div");

WriteLiteral(" class=\"source\"");

WriteLiteral(">\r\n");

            
            #line 76 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 76 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
                                 if (frame.PreContextCode != null)
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <ol");

WriteAttribute("start", Tuple.Create(" start=\"", 2656), Tuple.Create("\"", 2685)
            
            #line 78 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
, Tuple.Create(Tuple.Create("", 2664), Tuple.Create<System.Object, System.Int32>(frame.PreContextLine
            
            #line default
            #line hidden
, 2664), false)
);

WriteLiteral(" class=\"collapsable\"");

WriteLiteral(">\r\n");

            
            #line 79 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
                                        
            
            #line default
            #line hidden
            
            #line 79 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
                                         foreach (var line in frame.PreContextCode)
                                        {

            
            #line default
            #line hidden
WriteLiteral("                                            <li><span>");

            
            #line 81 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
                                                 Write(line);

            
            #line default
            #line hidden
WriteLiteral("</span></li>\r\n");

            
            #line 82 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
                                        } 

            
            #line default
            #line hidden
WriteLiteral("                                    </ol>\r\n");

            
            #line 84 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
                                } 

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <ol");

WriteAttribute("start", Tuple.Create(" start=\"", 3070), Tuple.Create("\"", 3089)
            
            #line 86 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
, Tuple.Create(Tuple.Create("", 3078), Tuple.Create<System.Object, System.Int32>(frame.Line
            
            #line default
            #line hidden
, 3078), false)
);

WriteLiteral(" class=\"highlight\"");

WriteLiteral(">\r\n                                    <li><span>");

            
            #line 87 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
                                         Write(frame.ContextCode);

            
            #line default
            #line hidden
WriteLiteral("</span></li></ol>\r\n\r\n");

            
            #line 89 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 89 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
                                 if (frame.PostContextCode != null)
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <ol");

WriteAttribute("start", Tuple.Create(" start=\'", 3339), Tuple.Create("\'", 3364)
            
            #line 91 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
, Tuple.Create(Tuple.Create("", 3347), Tuple.Create<System.Object, System.Int32>(frame.Line + 1
            
            #line default
            #line hidden
, 3347), false)
);

WriteLiteral(" class=\"collapsable\"");

WriteLiteral(">\r\n");

            
            #line 92 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
                                        
            
            #line default
            #line hidden
            
            #line 92 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
                                         foreach (var line in frame.PostContextCode)
                                        {

            
            #line default
            #line hidden
WriteLiteral("                                            <li><span>");

            
            #line 94 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
                                                 Write(line);

            
            #line default
            #line hidden
WriteLiteral("</span></li>\r\n");

            
            #line 95 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
                                        } 

            
            #line default
            #line hidden
WriteLiteral("                                    </ol>\r\n");

            
            #line 97 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
                                } 

            
            #line default
            #line hidden
WriteLiteral("                            </div>\r\n");

            
            #line 99 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
                        } 

            
            #line default
            #line hidden
WriteLiteral("                    </li>\r\n");

            
            #line 101 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
                } 

            
            #line default
            #line hidden
WriteLiteral("            </ul>\r\n        </div>\r\n\r\n        <div");

WriteLiteral(" id=\"querypage\"");

WriteLiteral(" class=\"page\"");

WriteLiteral(">\r\n");

            
            #line 106 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
            
            
            #line default
            #line hidden
            
            #line 106 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
             if (Model.Query.Any())
            {

            
            #line default
            #line hidden
WriteLiteral("                <table>\r\n                    <thead>\r\n                        <tr" +
">\r\n                            <th>");

            
            #line 111 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
                           Write(Resources.ErrorPageHtml_VariableColumn);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                            <th>");

            
            #line 112 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
                           Write(Resources.ErrorPageHtml_ValueColumn);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                        </tr>\r\n                    </thead>\r\n             " +
"       <tbody>\r\n");

            
            #line 116 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 116 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
                         foreach (var kv in Model.Query.OrderBy(kv => kv.Key))
                        {
                            
            
            #line default
            #line hidden
            
            #line 118 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
                             foreach (var v in kv.Value)
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <tr>\r\n                                    <td>");

            
            #line 121 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
                                   Write(kv.Key);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                                    <td>");

            
            #line 122 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
                                   Write(v);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                                </tr>\r\n");

            
            #line 124 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
                            }
            
            #line default
            #line hidden
            
            #line 124 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
                                                     }

            
            #line default
            #line hidden
WriteLiteral("                    </tbody>\r\n                </table>\r\n");

            
            #line 127 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
            }
            else
            {

            
            #line default
            #line hidden
WriteLiteral("                <p>");

            
            #line 130 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
              Write(Resources.ErrorPageHtml_NoQueryStringData);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n");

            
            #line 131 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </div>\r\n        <div");

WriteLiteral(" id=\"cookiespage\"");

WriteLiteral(" class=\"page\"");

WriteLiteral(">\r\n");

            
            #line 134 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
            
            
            #line default
            #line hidden
            
            #line 134 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
             if (Model.Cookies.Any())
            {

            
            #line default
            #line hidden
WriteLiteral("                <table>\r\n                    <thead>\r\n                        <tr" +
">\r\n                            <th>");

            
            #line 139 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
                           Write(Resources.ErrorPageHtml_VariableColumn);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                            <th>");

            
            #line 140 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
                           Write(Resources.ErrorPageHtml_ValueColumn);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                        </tr>\r\n                    </thead>\r\n             " +
"       <tbody>\r\n");

            
            #line 144 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 144 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
                         foreach (var kv in Model.Cookies.OrderBy(kv => kv.Key))
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <tr>\r\n                                <td>");

            
            #line 147 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
                               Write(kv.Key);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                                <td>");

            
            #line 148 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
                               Write(kv.Value);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                            </tr>\r\n");

            
            #line 150 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </tbody>\r\n                </table>\r\n");

            
            #line 153 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
            }
            else
            {

            
            #line default
            #line hidden
WriteLiteral("                <p>");

            
            #line 156 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
              Write(Resources.ErrorPageHtml_NoCookieData);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n");

            
            #line 157 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </div>\r\n        <div");

WriteLiteral(" id=\"headerspage\"");

WriteLiteral(" class=\"page\"");

WriteLiteral(">\r\n");

            
            #line 160 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
            
            
            #line default
            #line hidden
            
            #line 160 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
             if (Model.Headers.Any())
            {

            
            #line default
            #line hidden
WriteLiteral("                <table>\r\n                    <thead>\r\n                        <tr" +
">\r\n                            <th>");

            
            #line 165 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
                           Write(Resources.ErrorPageHtml_VariableColumn);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                            <th>");

            
            #line 166 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
                           Write(Resources.ErrorPageHtml_ValueColumn);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                        </tr>\r\n                    </thead>\r\n             " +
"       <tbody>\r\n");

            
            #line 170 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 170 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
                         foreach (var kv in Model.Headers.OrderBy(kv => kv.Key))
                        {
                            
            
            #line default
            #line hidden
            
            #line 172 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
                             foreach (var v in kv.Value)
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <tr>\r\n                                    <td>");

            
            #line 175 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
                                   Write(kv.Key);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                                    <td>");

            
            #line 176 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
                                   Write(v);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                                </tr>\r\n");

            
            #line 178 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
                            }
            
            #line default
            #line hidden
            
            #line 178 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
                                                     }

            
            #line default
            #line hidden
WriteLiteral("                    </tbody>\r\n                </table>\r\n");

            
            #line 181 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
            }
            else
            {

            
            #line default
            #line hidden
WriteLiteral("                <p>");

            
            #line 184 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
              Write(Resources.ErrorPageHtml_NoHeaderData);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n");

            
            #line 185 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </div>\r\n        <div");

WriteLiteral(" id=\"environmentpage\"");

WriteLiteral(" class=\"page\"");

WriteLiteral(">\r\n            <table>\r\n                <thead>\r\n                    <tr>\r\n      " +
"                  <th>");

            
            #line 191 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
                       Write(Resources.ErrorPageHtml_VariableColumn);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                        <th>");

            
            #line 192 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
                       Write(Resources.ErrorPageHtml_ValueColumn);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                    </tr>\r\n                </thead>\r\n                <tbod" +
"y>\r\n");

            
            #line 196 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 196 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
                     foreach (var kv in Model.Environment.OrderBy(kv => kv.Key))
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <tr>\r\n                            <td>");

            
            #line 199 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
                           Write(kv.Key);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                            <td>");

            
            #line 200 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
                           Write(kv.Value);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                        </tr>\r\n");

            
            #line 202 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                </tbody>\r\n            </table>\r\n        </div>\r\n        <script");

WriteLiteral(" src=\"http://ajax.aspnetcdn.com/ajax/jquery/jquery-1.9.0.js\"");

WriteLiteral("></script>\r\n        <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n            //<!--\r\n");

WriteLiteral("            ");

            
            #line 209 "C:\Users\lodejard\Projects\temp2\katana-working\src\Microsoft.Owin.Diagnostics\Views\ErrorPage.cshtml"
        WriteLiteral(@"
(function ($) {
    $('.collapsable').hide();
    $('.frame:first-child .collapsable').show();
    $('.page').hide();
    $('#stackpage').show();

    $('.frame').click(function () {
        $(this).children('.source').children('.collapsable').toggle('fast');
    });
    
    $('#headers li').click(function () {

        var unselected = $('#headers .selected').removeClass('selected').attr('id');        
        var selected = $(this).addClass('selected').attr('id');
        
        $('#' + unselected + 'page').hide();
        $('#' + selected + 'page').show('fast');
    });
    
})(jQuery);
");

            
            #line default
            #line hidden
WriteLiteral("\r\n        //-->\r\n        </script>\r\n    </body>\r\n</html>\r\n");

        }
    }
}

