//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.35312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Owin.Diagnostics.Views {
    
    #line 1 "WelcomePage.cshtml"
    using System;
    
    #line default
    #line hidden
    
    
    public class WelcomePage : Microsoft.Owin.Diagnostics.Views.BaseView {
        
#line hidden
        
        public WelcomePage() {
        }
        
        public override void Execute() {
            
            #line 2 "WelcomePage.cshtml"
  
    Response.ContentType = "text/html";

            
            #line default
            #line hidden
WriteLiteral("\r\n<!DOCTYPE html>\r\n<html");

WriteAttribute("lang", Tuple.Create(" lang=\"", 85), Tuple.Create("\"", 167)
            
            #line 6 "WelcomePage.cshtml"
, Tuple.Create(Tuple.Create("", 92), Tuple.Create<System.Object, System.Int32>(System.Globalization.CultureInfo.CurrentUICulture.TwoLetterISOLanguageName
            
            #line default
            #line hidden
, 92), false)
);

WriteLiteral(">\r\n<head>\r\n    <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(" />\r\n    <title>");

            
            #line 9 "WelcomePage.cshtml"
      Write(Resources.WelcomeTitle);

            
            #line default
            #line hidden
WriteLiteral("</title>\r\n    <style");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(">\r\n        ");

WriteLiteral("@font-face {\r\n            font-family: \'SegoeLight\', helvetica, sans-serif;\r\n    " +
"        font-weight: normal;\r\n            font-style: normal;\r\n        }\r\n\r\n    " +
"    body {\r\n            background-color: #00abec;\r\n            color: #fff;\r\n  " +
"          font-family: \'SegoeLight\', helvetica, sans-serif;\r\n            font-si" +
"ze: 18px;\r\n            margin: 0;\r\n            padding: 0;\r\n        }\r\n\r\n       " +
" .content {\r\n            position: absolute;\r\n            left: 50px;\r\n         " +
"   top: 38px;\r\n            width: 440px;\r\n        }\r\n\r\n            .content .azu" +
"reLogo {\r\n                margin: 0 0 65px 0;\r\n            }\r\n\r\n            .con" +
"tent .bodyHeadline {\r\n                margin: 35px 0 0;\r\n                font-si" +
"ze: 40px;\r\n                line-height: 43px;\r\n            }\r\n\r\n            .con" +
"tent .bodyContent {\r\n                margin: 10px 0 30px 0;\r\n                lin" +
"e-height: 22px;\r\n            }\r\n\r\n                .content .bodyContent a {\r\n   " +
"                 color: #fff;\r\n                    text-decoration: none;\r\n     " +
"           }\r\n\r\n                    .content .bodyContent a:hover {\r\n           " +
"             opacity: .7;\r\n                    }\r\n\r\n            .content .bodyCT" +
"A {\r\n                color: #fff;\r\n                display: block;\r\n            " +
"    line-height: 30px;\r\n                height: 29px;\r\n                width: 23" +
"0px;\r\n                cursor: pointer;\r\n                text-decoration: none;\r\n" +
"                position: relative;\r\n            }\r\n\r\n                .content ." +
"bodyCTA.longer {\r\n                    margin-top: 10px;\r\n                    wid" +
"th: 440px;\r\n                }\r\n\r\n                .content .bodyCTA div {\r\n      " +
"              position: absolute;\r\n                    overflow: hidden;\r\n      " +
"              width: 29px;\r\n                    height: 29px;\r\n                 " +
"   float: right;\r\n                    top: 0;\r\n                    right: 0;\r\n  " +
"              }\r\n\r\n                    .content .bodyCTA div img {\r\n            " +
"            position: absolute;\r\n                        top: 0;\r\n              " +
"          left: 0;\r\n                        border: 0;\r\n                    }\r\n\r" +
"\n                .content .bodyCTA:hover div img {\r\n                    left: -2" +
"9px;\r\n                }\r\n\r\n                .content .bodyCTA:hover {\r\n          " +
"          opacity: .7;\r\n                }\r\n\r\n        .wrapper {\r\n            wid" +
"th: 100%;\r\n            height: 100%;\r\n            overflow: hidden;\r\n           " +
" min-width: 1200px;\r\n        }\r\n\r\n        .innerwrapper {\r\n            width: 38" +
"4px;\r\n            height: 100%;\r\n            margin-right: auto;\r\n            ma" +
"rgin-left: auto;\r\n        }\r\n\r\n        .browser {\r\n            position: absolut" +
"e;\r\n            display: block;\r\n            top: 400px;\r\n            width: 384" +
"px;\r\n            height: 305px;\r\n            cursor: default;\r\n            z-ind" +
"ex: 10;\r\n        }\r\n\r\n            .browser div {\r\n                width: 384px;\r" +
"\n                height: 305px;\r\n                position: absolute;\r\n          " +
"      top: 40px;\r\n                left: 100px;\r\n                font-size: 200px" +
";\r\n                text-align: left;\r\n                -webkit-touch-callout: non" +
"e;\r\n                -webkit-user-select: none;\r\n                -khtml-user-sele" +
"ct: none;\r\n                -moz-user-select: none;\r\n                -ms-user-sel" +
"ect: none;\r\n                user-select: none;\r\n            }\r\n\r\n        .bulb {" +
"\r\n            position: fixed;\r\n            margin-left: 20px;\r\n            top:" +
" 0;\r\n        }\r\n\r\n        .light {\r\n            position: fixed;\r\n            ma" +
"rgin-left: 53px;\r\n            top: 0;\r\n            opacity: 0;\r\n        }\r\n\r\n   " +
"     .bottom {\r\n            position: fixed;\r\n            bottom: 0;\r\n          " +
"  margin-right: auto;\r\n            margin-left: -303px;\r\n            z-index: -1" +
";\r\n            height: 202px;\r\n        }\r\n    </style>\r\n    <script>\r\n    </scri" +
"pt>\r\n</head>\r\n<body>\r\n    <div");

WriteLiteral(" class=\"wrapper\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"innerwrapper\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"light first\"");

WriteLiteral(">\r\n                <img");

WriteLiteral(" src=\"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAARIAAAESCAYAAAAxN1ojAAAAGXRFW" +
"HRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAACKhJREFUeNrs3TFPG0kYgOE1kou4IIVTUITiX" +
"JAiFFxBk/8vGopQQBEKKFyci7jAhRsX3E4YB3I5Asva3p2Z55EspJNOOq/3Xn8zu7arCgAAAAAAAAAAA" +
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADI1MAhILi/v9+v/wwb/murwWCwc" +
"PQQknJCMa7/jOLj3X/+bsKqfiye/F3Gx6KOzcorICSkGY0P9WM/hmK/4/+kZYxLeHwXFyGh3+EYx0cK1" +
"lGZh4ewCAm7D0fYyziIjxCOYQZPaxajMqujsvQqCwnbj8dB5k83TCtTURESNheQdTgOCz0EsxiUqbNBS" +
"Gg+fUzqx8dqc1dVUreKU8qtKUVI+HNAQjSOCp4+mkwpN3VQ5g6FkPAYkHGMh4A0E0LyTVCEpPSAhPs7j" +
"qt0LtkKCkJiCVNEUC7dti8kuQdkvYl65GhsVdiUvXKTm5DkGJFwCfdz5SrMroSIXNcxuXEohCSXZcxJZ" +
"R+kK2GZ89VyR0hSjsh6GTN0NDp3EycUyx0hMYVgOhGSMiJyECNiCumvMJl8cxiEpI8BCeEIm6ku6aYhX" +
"Co+t9QRkr4tZU6r7r9AiGZCRM4sdYSkDxEZx4hYyqTrwqeLhaTLiIRlzIkjkYVpHZMLh0FIdh2REBD7I" +
"XmZxenEvomQbD0gNlXzFvZLzsRESLYdkS+VTdUSYnLuC5SERERoyxUdIRERxERIRAQxERIRQUzKsucQi" +
"AgvCufC3/GcQEga+SwiPBHOhS9iIiRNphE3m/FcTE4dBiF5TUT8LAR/Mo5vNAjJsxEJH8BzkvCSw/iGg" +
"5D8FpGRsZUGTuIbD0LyMyLDylcB0NypzVchecoVGt5iaIoVkvU0Er5j1XqXtwqbr5+EpOyIrL/tHdo4K" +
"n2/pPSJxLe9s7FzqeT9kmJDEn+8yq47m7L+YXghKWxJ44e82bRJqUucUicSSxoscYSk1TRyYEnDlpc4E" +
"yHJOyLrL26GbTqKy2chyXUNG98xYBfLZyHJcBqxwcoujUvaeC1pIhERdu1YSPKaRsLnaNwGz67tl/J1A" +
"6VMJMfOaUzCQtJmGgnrVJd76cqohKmkhInEkgZTiZC0mkZGQoKpREi8E2AyFpJOp5GhaYQeyfq+kpwnk" +
"olzF1OJkLT10XlL30KS6yeDswxJ/ISvz9RgKhGSVg6cr/TUX0KSxjRik5U+G8WPbAiJaQQsb4QEnKNC8" +
"sKyRkiwvBESpcfyRkiEBIo7V3MLia8LIKXlTTb3OmUTkvg5Br9Vg6lESFr54LzEBC0kXhSEREi8KNDQM" +
"JfLwFmEpNQfbsaSXEi8GBCYSLwY0Np7IREScO5mFBJfYkSyctjj2/MigDdCE4lpBOewkHgRIP19khxC8" +
"s55SOKS/4yYiQS6Z7PVRAKYSKAHUv/MzZ6XEHoh6X2SpEOS4++DgJCoOBS5RLe0ASEREkBIACEBEBJAS" +
"AAhAYQEQEgAIQGEBHi0EhIHH9q6E5KODAaDhfMPhASwtPECgOk6j5BY3oCQmEgoXvJvhiYS8GYoJLWl8" +
"5DEzYVESMBEYmkDnbtL/QkkH5LBYLAyleDNUEi8EJRsGd8MhURIoOxzN5eQfHc+kqh5Dk/CRALdusvhS" +
"WQRkrjGFBNSPHdNJJY3YFmTW0jmzksSMxMSIQFTdG4hifskYkIqljl9w19u35A2c35ighYSIaEUWZ2rW" +
"YWkHhXDZ25cBqbvVvW5KiQ9N3WeYhoREi8SQiIkvVjeuHpDXy1zW9bkOpFY3mAaEZKNTCUhJL5dnj66F" +
"RJTCbQxj0tvIVF+eLObXJ9YtiGJ5XcFh77IcpO1hIkk63cAknOd85PLOiTxS2NcCqZrq3gBQEgS9s15T" +
"Mey36/LPiSmErqeRkpYYu8V8mKaSuhsGsnhd2uExFRCd8KVmiLexPYKelFNJezadSlPtJiQxKnE3a7sy" +
"iL3KzWlTiTrdwifwWEXLkt6skWFJN7t6tZ5tm2ayw9fCcnzMQl7Jb6OkW0JE+9VaU96r9AX+9L5zpZcl" +
"XC5V0iqnxuvPofDps1L2mA1kTwIG69L5z4bXNJclPrkiw1JHD/Pnf9syEWuX1okJC/HZFEVdNMQWzPL+" +
"btGhOR1MQlXcdw+z1stS17SCMmvzis3qtHcj+VxiVdphOT/p5JwIpw5EjR0FZfHxROSx5gsjKg0MC31U" +
"q+QvByTcGI4OXhJuF/Em46Q/DEm4QSx+cpzwuTqtgEheZXzyudx+J3NVSFpNJWsN1/FhKcROSv5pjMhe" +
"XtMvlYuC/MYEW8sQvKmmCziZCImZRMRIRETWrkQkVf8f+IQvM79/f1+/edL/Rg6GsUsZ85L+6YzIdldT" +
"E7rx8jRyD4iljNCstWYDONksu9oiAhC0jYmYTIZOxpZWcTljEu8QrLToJzUfw4diSzMKzebCUmHMZnUf" +
"z47Ekmb+uyMkPQhJuO41HFFJy0/fjrCp3iFpE8xsQmblmVcythUFZJeBuVT/efIkei18P2qF/ZDhCSFp" +
"U7YiHW/iaWMkNB6qRMmk4mj0QvzqvCfjBAS0wmmECERkx/TyaSyd7Jr06rQ3+IVkryDMorTiTtitytci" +
"bn0gTshKWG5c1y5VLxpYf/j2jJGSEoLymFc7tg/aScsXW7jryYiJILiaDQPSP24sQ8iJPwalPCwh/KKJ" +
"Uz18OPdAiIkPBOUcQyKTxb/ah6nj5lDISS8PijDGJO/Cl72hOkjhOPWzWRCQvuo7MeoHBQQlVWMx8z0I" +
"SSIingICYlEZRSDMo6PlL4TZR4f//g4v5DQv2nlQ/Vws9v7qj83vYX9jUUMx527ToWE9OIyjkugUfV4a" +
"Xlbl5gXcZkyj3/vwj9zmVZIyH+CWS+H3jdYGq0j8XAimTAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHL0rwADANq3ok68n5URAAAAAElFTkSuQmCC\"");

WriteAttribute("alt", Tuple.Create("\r\n                    alt=\"", 7465), Tuple.Create("\"", 7533)
            
            #line 168 "WelcomePage.cshtml"
, Tuple.Create(Tuple.Create("", 7492), Tuple.Create<System.Object, System.Int32>(Resources.WelcomePageImageText_LightBulb
            
            #line default
            #line hidden
, 7492), false)
);

WriteAttribute("title", Tuple.Create(" title=\"", 7534), Tuple.Create("\"", 7583)
            
            #line 168 "WelcomePage.cshtml"
, Tuple.Create(Tuple.Create("", 7542), Tuple.Create<System.Object, System.Int32>(Resources.WelcomePageImageText_LightBulb
            
            #line default
            #line hidden
, 7542), false)
);

WriteLiteral(" width=\"274\"");

WriteLiteral(" height=\"274\"");

WriteLiteral(" /></div>\r\n            <div");

WriteLiteral(" class=\"browser\"");

WriteLiteral(" style=\"opacity: 1; visible: true;\"");

WriteLiteral(">\r\n                <img");

WriteLiteral(" src=\"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAYAAAAExCAYAAAB1UXVvAAAAGXRFW" +
"HRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAACDJJREFUeNrs3c1vFGUcwPEHKE2JgghEqR5aE" +
"0gARYEY09REiV4MHDTx4MEDGDlw5T+Qv0CPHCDiH2ACB4wHXwgJBI3BorwlEqQHKMiLlZpYWl6cX9uVt" +
"bB0Zzu723Y/n2SzUJpls5M835lnnpltS5N8vGPne9nTtuyxOXssTQDMVn3Z42D22L9v756Lk/9xXtnAv" +
"yF7+jx7bPCZAcw5u7MIfFL+gwVlg//32aPbZwQwJ23etOnV7p9P/HSw9IP5E8+x52+6B2Bu2z4xzT8eg" +
"Owv25NpH4BW8Wn5EcC7Pg+AltE9Me2f2tL4ap+6+3vR02lo0f9nmdrvDKfltwZsDoDGinG/LwJQl7n/G" +
"PD7n12b+p9ZlwaWvfDY310+NJBW3vw9dWaPrqtnbBqA+noze3zWVvSrxmD/86q3pxz0y91Y3Dn2ON3Vm" +
"57858/0Uv+xtPrSidQ+OmwzARRvbMe/sADcWNKZflizNdfAX+nI4Xj2OqeyGPSc+8oRAUDxNhQWgNPdv" +
"WODdpEiBN9s/HDsSKDn3CFHAwAFHwHMn+6rHFn/fuGDf7nfnt+UvnptRxpZ2GGTARRoWgGIwT8G6HqL8" +
"wMiADBDAtCowV8EAGZQAGLgb+TgXx6BCA8ATQjA2CqdtVub9objuoL+Z9fZcgCNDsDxtVvSSFtzp2HiK" +
"MBUEMD05FoGGmv8Yw+8FmsWL0grOx7uzfGbd9Lw3fu5XisCdLrr9bTx/LdT/u4rr7xsKwMt4+TJX+oTg" +
"Frn/TcsXZDee679oZ8fuDySe/AvOdXdW1UAAHi0qqeAYsqllgC8s3JhxcG/b/BuzW88jgKcCwBoQABqm" +
"fqJgb9nWVvhg/+D97TWFgSoUdVTQHnv8RODf0z9lIvpngOXR9O5obuFvPnp3ncIQACqEMs/pzv47+8fS" +
"VeG7xX25uM9xdSU+wQBNPkIoGPBvGzwXzi24meyw9fuZP+eUvcT+VaeDo7cT4OjlU8Ux8Vh8T0CANQpA" +
"NUM/tu72h+51DPEyeBaRDgOXxu1pQAKNr+IF5lq8K+nPFNTABQcAABaNABxgnfPhduFLO3MK75CEoD8C" +
"v1O4Fjfn9LDK4DC11dG05Xb+VcAxUlgAJoYgFhpU81KoEoRiJPARV0AVm750ICtCFCDqqeAluUYaCsN9" +
"I+6PmA6YvrHNQAAdQ5A3rX2EYGY9qlnBKz/B2hAALqunkntd/LtbcetnsenhOoTga4/ztqCAPUOQCkCe" +
"cVUUKUI1HpxWIjpn1reDwDjcq0C2nT+u5puCR0RGL478sgLxZYunPfYWz087r1UI8+XIwAIwGP2uldfO" +
"lFTBOIOoEXdBbT0PgCoXe4LwXrOHcp9LqBob/z6pS0H0OgAxLLLZg7AL/Yfs/oHoBkBCHHytdo5+CLFR" +
"V89Zw/ZagDNCkCIL2Rv5Dx8DP5bftxriwE0OwAhpoIacSQQUz4x+LvqF6A4074ZXBwJxG0ijqx/P420d" +
"RT+BiMw8X8AMMMCEOKcwAc3L6Tja7bWtES00l5/DPxO+ALM4ACE0uqg2GM/seqtmkMQA36cW7DOH2CWB" +
"KAkLtKKEMT1Av3PrBu7hXQ8Kn11Y1xT0JkdPcTA33X1rC94AZitASg/Ipi8Jx8RGFq09L+Bf/kt9/IHm" +
"HMBqHR0YA8fYGbwpfAAAgCAAAAgAAAIAABzyJSrgG50rEhHO1/3SQHMAiuGr6fegaOOAAAQAAAEAAABA" +
"BAAAAQAAAEAQAAAEAAABAAAAQBAAAAQAAAEAAABAEAAABAAAAQAAAEAQAAAEAAABAAAAQBAAAAQAAAEA" +
"AABABAAAAQAAAEAQAAAEAAABAAAAQBAAAAQAAAEAAABAEAAABAAAAQAAAEAQAAAEAAABAAAAQBAAAAQA" +
"AAEAAABAEAAAAQAAAEAQAAAEAAABAAAAQBAAAAQAAAEAAABAEAAABAAAAQAAAEAQAAAEAAABAAAAQBAA" +
"AAQAAAEAAABAEAAAAQAAAEAQAAAEAAABAAAAQBAAAAQAAAEAAABAEAAABAAAAQAAAEAQAAAEAAABAAAA" +
"QBAAAAQAAAEAAABAEAAABAAAAEAQAAAEAAABAAAAQBAAAAQAAAEAAABAEAAABAAAAQAAAEAQAAAEAAAB" +
"AAAAQBAAAAQAAAEAAABAEAAABAAAAEAQAAAEAAABAAAAQBAAAAQAAAEAAABAEAAABAAAAQAAAEAQAAAE" +
"AAABAAAAQBAAAAQAAAEAAABAEAAABAAAAQAQAAAEAAABAAAAQBAAAAQAAAEAAABAEAAABAAAAQAAAEAQ" +
"AAAEAAABAAAAQBAAAAQAAAEAAABAEAAABAAAAQAQAAAEAAABAAAAQBAAAAQAAAEAAABAEAAABAAAAQAA" +
"AEAQAAAEAAABAAAAQBAAAAQAAAEAAABAEAAABAAAAQAAAEAEAAABAAAAQBAAAAQAAAEAAABAEAAABAAA" +
"AQAAAEAQAAAEAAABAAAAQBAAAAQAAAEAAABAEAAABAAAAQAAAEAEAAABAAAAQBAAAAQAAAEAAABAEAAA" +
"BAAAAQAAAEAQAAAEAAABAAAAQBAAAAQAAAEAAABAEAAABAAAAQAAAEAEAAfAUBrapvyF+6NphXD131SA" +
"LPAkpG/igvAU9mL9Q4c9akCzDGmgAAEAIAWMSgAAK2pTwAAWtPFUgAGfRYALeVkKQCHfRYALeVwKQBf+" +
"CwAWkbfvr17xs8BZH844CgAoGXsLv2hdBJ4V3IuAGCu2z+x0/8gABOHAxsdCQDMSbGDvysb6z8q/+G8y" +
"b/18Y6dm7Onbdkjnrt9bgCzVuzUH5zY839oludfAQYAY+bWx82mLokAAAAASUVORK5CYII=\"");

WriteAttribute("alt", Tuple.Create("\r\n                    alt=\"", 10663), Tuple.Create("\"", 10729)
            
            #line 171 "WelcomePage.cshtml"
, Tuple.Create(Tuple.Create("", 10690), Tuple.Create<System.Object, System.Int32>(Resources.WelcomePageImageText_Browser
            
            #line default
            #line hidden
, 10690), false)
);

WriteAttribute("title", Tuple.Create(" title=\"", 10730), Tuple.Create("\"", 10777)
            
            #line 171 "WelcomePage.cshtml"
, Tuple.Create(Tuple.Create("", 10738), Tuple.Create<System.Object, System.Int32>(Resources.WelcomePageImageText_Browser
            
            #line default
            #line hidden
, 10738), false)
);

WriteLiteral(" width=\"384\"");

WriteLiteral(" height=\"305\"");

WriteLiteral(" /><div>:-)</div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"light second\"");

WriteLiteral(">\r\n                <img");

WriteLiteral(" src=\"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAARIAAAESCAYAAAAxN1ojAAAAGXRFW" +
"HRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAEf1JREFUeNrsne1LHFkWh2+3otGxscGQTHSCM" +
"kLCZtj9MB/2//+8HxZ2QjJEcDE4ZlaJ0KFNxzQ22TrmVKY1/VbVt6ruPfd5oOjJQKL10k/9zrm3brUcm" +
"OHLly9r2cd6tnWybSXbNvRzM5BfcZhtn7PtU7aNsq0vn61Wa8DZi5sWhyBaaWyqKPLPTuS71FfRiFQ+Z" +
"XLpc5YRCfiVxoqKomNEGosiUrnSz34mlyFXAyKBcuLYCqg0CaE06ucbYkEkMLlUEWl0E0ocvhLLJX0WR" +
"JK6PHZUHmsckaWQ5m1PtkwqPQ4HIkEegFQQCUyQhwjjoQoEedQvlUvKH0QSs0B2VB70PMJARHKhSWXE4" +
"UAkoaePxyqQFY5I0KXPBSkFkYQmEEkdj9zX3gfEQ1/LnksOBSJpunwRgTDXI25kTso7yh5E0oRAdh3NU" +
"4tlj/RRzhEKIkEggFAQCQIBhIJIbAlEmqdPEQhCybZTmrKIpKhAZBTmiWMOCNxFmrInLHOASOYJZEUTy" +
"A5HA2bQV6HwBDIi+U4i0gORoVwmksGiSP/kXer9E0TyVxnzk2MuCJQvd05TfkAwaZFoGZOnEIBl6alQk" +
"it3khUJozFQESMtdS4Qif0UQjMVqiapZmxSItFeyAEpBGpMJ0nMPUlGJJlEJIXQC4Em6Gk6MTuyY14ku" +
"j7IoWNEBppFSpxjq+ufmBaJNlSllGFeCITCqcVGrFmRUMoApQ4iWUYgkj6eUcoApQ4iKSuRTZUIpQzEg" +
"JlRHTMi0fVCDrg2IUL+zGTyDpE0LxH6IRA7l5pOouybRC0SZqmCMaRfchSjTKIVCU1VMEqUTdgoRcIkM" +
"zDOSJNJNDKJTiSMzEBCMjmOZUnHqESCRCBBTmIYHo5GJEgEkAkiQSIAhmUSvEiQCED4MglaJEgEIA6ZB" +
"CsSJAIQj0zaSAQgOg502VBEMkMiK0gEYC6HesNFJEgEoDS335VQZBKMSHh2BqCUTA71u9MowTRbs4Nx4" +
"HiKt2m2sm214N+5ybYrDl2jNP7UcBAiYT2R2pDFsNez7cHYlv/ZByKVj2Nyuc62z/rfNxz+SullIjlOV" +
"iSsbFapNLY1ZazrZ5Ncq2REKh+QSyVcZDI5TU4k2ij6G+ffqzjyzxjIpdLTT8SyPI3MMWlMJNog+rtjh" +
"KYs0suQNPdQxbFqYJ8uVSqXmmCgHL/XvZZJkyKRJMIITXl5WG9MS1o5RyqlkFXWXtfZfG1EJDRXC5PL4" +
"3Gi+y8yea9igcXoZyI5MisSfY3mIed5ofSxp/J4wOG45UZlckZKWYjaXnNRq0h0rdUXjr7ILEQa+wmnj" +
"yIpRYTS41DM5KiO5RrrFgl9kel0VR4IpBgy2vMWoUxF+iQvq+6X1CYS+iJT2dJSb5tDgVAqovJ+SS0i0" +
"Ueen3E+KWFqEorM8GTa/l3kLX4X0YpE54tIX2SNc3lL3kTd51BUyrkKhUluf5U4MiQ8jFUkB46H8XJ2t" +
"IxhFKYebrTcOeNQ3DLIRPJ7dCJhqPdOGfPc0QdpCilzjih3bqlkSLgykVDSfCMvY1a5hhvnTBNK6uXOS" +
"98lTpUiSX2UhhRCOgkV76M4lYiEUZrbXshzUkjQvNUtVbyO4lQlklQnnok4pCfEkG4cyFDxq0RLHa8T1" +
"byv2ZpJ5FGiEpFS5h9IJCqk7Pyna37RpyaQHuZTX/+YV5Fog3U3wZMio1O/JnpBWkiRvyZ6A9jx9X4c3" +
"4nkqUvvgbzHmkToh8TNc91S40lQIlGz7XDxQeQ3hV8Suyl0dN3kYBLJk4QO/qoKhH6IwbifYMLcXfbdO" +
"F5EojNYO4kc9FVHU9U6W3qOU3mUYW3Z69lXInmayAHPJUJTNQ2ZpNRAf7RMKllaJFpfpTANHomkR0rnf" +
"GWZVOIjkexyQQHn3gRPdDnUekWSSBpBIpDSNVAqGLSb+KFcQBDptfDM2R/N2SmTSkqLJJE0cohEYIx8N" +
"Me6TAoHhHadPywymCcC02Tyi/F97BYdwSklkgTSCK+FgFlsO9szmguP4JRNJJYXLOo6pr0DN5tC80oKi" +
"0SfqbG6TIDMZHzBdwQKlL9dw6lk4X0rk0isppFVlQhP8UIRLF8zC/dBC4lEh4WsGpgRGih7A7LafF3T5" +
"+i8JxKrNeGOo7kK5ZHm677h74Z3kVhcbyRf7R1gGfaNpvXuIhPUFhaJDvlaXP2M1d7BF1Znvj70mUgsp" +
"pE9x3tnwG+6tVjizP3uLyQSjTYdTjrAQjcnayXO3KbroonkocETTkkDlDieUknbxz8S6UGhpIEq0+6es" +
"X2a+fzNXJFkf1lmsVp6riZ/Gx5Alew7e2u+dpdJJNbSyJ5LZ1FfaL58RiTz/nKkkZMGK9TFtrHvz9Typ" +
"p1YWYNEoG5+TiGVzEsklsoaeY6GafDAddeASCzFMhqsQBKuqLxpJ1LWdB3DvdAcD6ynkvacSGYFShogl" +
"fijU0QkVsoaa3cD4DqMI5FoDWTl2RpGaiAUfjSyHyva+pibSKxIZJU0AgFhaV5JNyWR7HHtQmBYubFtL" +
"SKSLU4aQGXXpIUngzszRaL9EQuvm5DJdDxTA9zgKkJfTTM1kVgpax5yvQIldz2pxKpIaLJCyDww0j7Ym" +
"iWSDSNlDQDlTbVsWk8klDXAza56vs0nuSOS+5NMIi5rSCRAeVMPG5MSCWUNAOVN4fKmPa3moawB4KaXc" +
"iJhuQCIqbyJfa5TZ5JIYm+0yvx/3lUDpJIakRfotcf/QBoBaOTmFzvr44lknZMCwM2vTHnTNlTWkEggR" +
"qQUj30YeGVcJCukEQBugCXYGBfJBicDoBFiTyTrlhLJFtcjRMoPkf/+a+Mi2eRkAHATLMOtSKa9zzMyW" +
"MQIYibqHl/bSBqh0QqxE/X0izYnAYBE7UskG5wEgEaJuk+SiyT251MQCcRO1N9BK6UNIoHYiXoelJXSh" +
"h4JQAAiiX34l0QCFoi2T9Lm3AEEQ7R9EgsiYWo8ACJJ1+IA94i212dlZiuABaLt9VlptgIApQ0AIBIAQ" +
"CQAAIgEABAJACASAEAkAACIBAACEUmfQwHQODckEg4+wLJ8RCTNccX1B4BIAMBIaTPiBACQrpcVySdqS" +
"wBIvbQhkQBpBJGkfRIAXOTtBSvzSK65DiFyeiSS5vnMdQiU582LZEBpA9AoUQ8Y3Iqk1WpZGP6lvAFuh" +
"gGUNkOMDtAI11ZKGyH2PgPlDXATbIbRuEhin5T2gesRIqUX+e8/GBdJ7H0SEgmQSJphOC6S2OeS3CATI" +
"JE0L5KRgRNCeQNcs02WNq1Wa2Bgh3pclxAZ7w3sw/D+zNbYyxsSCXDN1oyEkPsiiX0uyQ0ygYiQ+SOx9" +
"/Vuw8d9kVgob95zfQJppL6yZpJIPhnYsUuuT+CmVxuD70SS1ToWXkthIS6CfW6M3PSuJiUSK+XNOdcpk" +
"JyrJx/tbU8zDCcJgLJmDt8qGKuJRMobRm8g5OvTTFkzTSRWXt/5P65XIDFXymCqSLKaR4ZzhgZ2Uvokr" +
"C4PIXJmZD9mljaWUglNVwiND87Gan6D8ZUVrYvkjOsWAuMPI/txZ1DGukisNLWA6zE0enNFon2SgZEdJ" +
"pVAKLy1siP3J6+2F40ukZuToWBoGmn8nxv6TrlFRWKpJHjLdQwk4wZEolNfR4Z2nFQCTaYRSyLpF0kkE" +
"81DKgEolUaszGkaaA81WZGQSqAJro3dxCa2PGaKJDNPz1B5QyoBrjk/N+RiIjGaSpjtCnVxZex6m1jWp" +
"CiS/A7BMzhQB/81tj9TR3LnisRgeSM1K5PUoGrODd6Ee6VFMs9EEacSlmOEqpDEe2xsn/rTypqURWIxd" +
"kI4HBssn2c6YCGR6OS0gbED06PEgQr44Ow19EfzyrR2gX/swuBJlxLnmmsfPJY0bwzuV2987ZFlRWKt6" +
"Zqf+Ndc/+CJN0ZvTHNDxMIiUSNZfEn3lWOiGvjpIVjsJQ7yV074SiRWy5u8xGH6PJTl2mhJs/B3vpBI1" +
"Ex9owfslWOiGpQvjy1eO6PsO79QymqX+McvDV8Qv/G9gIIcO7tzkhauQAqLRA01NHrgrgxHVPDPubP97" +
"NbC+9Yu+QPecXFA4nwwftO5nDfk60MkFoeCx3njaL7C7OT6yvg+FgoLpUSiprowfiBfOZ7Hge+x3FwdT" +
"yOF2hftJX7YufFUkjdfkQncvyasz4Yu3LooLZJEUolcOEeOYWFI58ZSOI0sm0hSSCV5PfwbMkmeVNJpq" +
"YGUpUSSSCpBJvAmEYmUSiM+EkkqqQSZpF3OpDIdoPS0jqVFoqnkNJEDncuEpQfSkUgvkf0tnUZ8JRLrs" +
"10nyeTfjtGcFCSSyjleOgy0Pf4ypwleaExa40ZhgYsis1grFYmuNt9P6OCLTP7jmE5viQ8Jlq7D7Lu79" +
"CMvbc+/1EmCF5909I/5DkbPud4YUmume6kkvIpEmzUXCV6EZ44RnZiT5RuX5lPffa0kwhKJIjFplOBJk" +
"RPyL0cTNiauXVrDu5VVEK0qfrsvX750s4/DhC/Qfd0gXC41haSaIv/00RupVCQqk2fZRyfhC1VkKsfgA" +
"d/Z4EqZY5d2k1warC99/oNVimQt+3iRbSsJn7BVTSZ7fH+DIF+MKPUJhUeZSLyOsLaq/G0zmTzKPp5y/" +
"ZJOSCHBIHNGvM/5alX9W1Pi3Ekne47eSd2cO5vv4i1V0mTb62UnnzUlEkqcu0gqeZ5t2xyKSpHRM3lRf" +
"I9DUV1JU5tIVCY72ccB5/G7cufnbNviUHhF+h9vKWPqKWlqFYnK5FC/PHCXx1ru0D9ZDildzhyvX52Ev" +
"Hbz9yp/QJ0iWdESZ43zilAqEMiZow8yiZGWNIMqf0irzj3KZCJN12ec27lC+dHRQ1m0hLlEIDM5WfS1m" +
"9GIRGWym3084fzOpatSecyhuIPMBfnD2X11rE9ksaKTOn5Qq4m9o19SiFWVyV7CZc+1iuPMMZlsUQZa0" +
"tTy3FtTIqFfUo4tlcpOAlK5UXm8J30Uppa+SOMiUZlsuq/9EuaXIBXk4ZdjX8sDBC8SlQnzS/zwQIUi5" +
"eK2lkOxID2PnoqDJRiWx+tTvVGIRGUiz+I84vx7Tyvb+vmDC2fSm/Q3Pqo48k/wRy+TSCOr9bVC2PtMJ" +
"gd6R4XqkLSyruklb3RXNcR8pXV6T8uVj/r/GKatjlqbq6GKRPok0i/Z5HpoLMHk5dAPBUqjXBLf7ogcy" +
"kYQebxsSiLBiGRMJozkABSXSK0jNJNoh3I01KbHLs31XgHKcty0RIISicrkts5DJgALcVLVsgBRi2RMJ" +
"rwnBmC+RIKZa9MO8QipZU+4VgAmchqSRIIVicrkEpkAfIc8iBfcS+haoR81Zr8C3JFIkDfXVgxHD5kAh" +
"CuRaESCTACJhCuRqESCTCBRTkPsiUQtEpVJV2XC8gNgnZPQRmfMiERlwlomgEQQCTIBmMLtoyKhzFg1L" +
"xKVCU8NgzWJHIXw7ExSIhmTyYFjMWmIm0bXE0leJGNCYaU1iBVZx+UkVomYEonKhOFhiI1G1lhFJPNlQ" +
"hMWYmCkKcTEqnIti2dI+ybyEq4O1ysEiPRD3sbYVE1KJGNC4fWgEBoyN+Q05n5IciJRmXQ0nVDqQNOlz" +
"GlMk8wQCaUOUMogkgqFIsPDu6QTqJGLTCCn1neyldpZ1VGdfcdsWKiWoQtocWZEUp1QaMRCZSkk295Za" +
"6gikukykZdxHTh6J0AKQSQehELvBJbFxAxVRLK8TEQi8rwOLzOHIvQ1hQxTPgiI5HuhSJnzk6MZC/PLm" +
"FMrU9wRSXVC2dFyh5eawzjSQL1IuYxBJOXKncfu6/IE9E/A5PR2RFKvUHYd652kLJB3qfdBEIk/oaypU" +
"GjIIhBAJN6E0qXkQSCASHyUPPRQEAgi4RB4E0rXMcoTI7ejMNl2ThMVkYQkFRHKjmNV+9CRR/ovrK4Pg" +
"kjsCGVNy54uKSWo9NFTgQw4HIiElAJFkGnskjx6lC+IxIJQ8l5KF6nUUrrk8qB5ikiQCiAPRAJFpNJxz" +
"E0pSk+3PvJAJHBXLJsqlC3HokuTUseVpo4+hwORwOJi6ahQRCybiSWWvopjoKmDZikiAY+JZUOlsmEot" +
"Yg0hnnqYIgWkUD9cpG5KusqlTXdQkwvIxXFcEwaQ6SBSCCOBLOiclnX/70xJpl1t/ykOZHC57E/X+nnT" +
"bZ9EoEgC4DE044mHoCJ/F+AAQAgl3zNeDGxuQAAAABJRU5ErkJggg==\"");

WriteAttribute("alt", Tuple.Create("\r\n                    alt=\"", 17199), Tuple.Create("\"", 17267)
            
            #line 175 "WelcomePage.cshtml"
, Tuple.Create(Tuple.Create("", 17226), Tuple.Create<System.Object, System.Int32>(Resources.WelcomePageImageText_LightBulb
            
            #line default
            #line hidden
, 17226), false)
);

WriteAttribute("title", Tuple.Create(" title=\"", 17268), Tuple.Create("\"", 17317)
            
            #line 175 "WelcomePage.cshtml"
, Tuple.Create(Tuple.Create("", 17276), Tuple.Create<System.Object, System.Int32>(Resources.WelcomePageImageText_LightBulb
            
            #line default
            #line hidden
, 17276), false)
);

WriteLiteral(" width=\"274\"");

WriteLiteral(" height=\"274\"");

WriteLiteral(" /></div>\r\n            <div");

WriteLiteral(" class=\"bulb\"");

WriteLiteral(">\r\n                <img");

WriteLiteral(" src=\"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAVoAAAKSCAYAAACTAhMyAAAAGXRFW" +
"HRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAyRpVFh0WE1MOmNvbS5hZG9iZS54bXAAAAAAA" +
"Dw/eHBhY2tldCBiZWdpbj0i77u/IiBpZD0iVzVNME1wQ2VoaUh6cmVTek5UY3prYzlkIj8+IDx4Onhtc" +
"G1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IkFkb2JlIFhNUCBDb3JlIDUuMy1jM" +
"DExIDY2LjE0NTY2MSwgMjAxMi8wMi8wNi0xNDo1NjoyNyAgICAgICAgIj4gPHJkZjpSREYgeG1sbnM6c" +
"mRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4gPHJkZjpEZXNjc" +
"mlwdGlvbiByZGY6YWJvdXQ9IiIgeG1sbnM6eG1wPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvI" +
"iB4bWxuczp4bXBNTT0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wL21tLyIgeG1sbnM6c3RSZWY9I" +
"mh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9zVHlwZS9SZXNvdXJjZVJlZiMiIHhtcDpDcmVhdG9yV" +
"G9vbD0iQWRvYmUgUGhvdG9zaG9wIENTNiAoTWFjaW50b3NoKSIgeG1wTU06SW5zdGFuY2VJRD0ieG1wL" +
"mlpZDo2OEMyQkI4N0Q4NzIxMUUyQTdDN0Y3QzMzMkU0QTgyQiIgeG1wTU06RG9jdW1lbnRJRD0ieG1wL" +
"mRpZDo2OEMyQkI4OEQ4NzIxMUUyQTdDN0Y3QzMzMkU0QTgyQiI+IDx4bXBNTTpEZXJpdmVkRnJvbSBzd" +
"FJlZjppbnN0YW5jZUlEPSJ4bXAuaWlkOjY4QzJCQjg1RDg3MjExRTJBN0M3RjdDMzMyRTRBODJCIiBzd" +
"FJlZjpkb2N1bWVudElEPSJ4bXAuZGlkOjY4QzJCQjg2RDg3MjExRTJBN0M3RjdDMzMyRTRBODJCIi8+I" +
"DwvcmRmOkRlc2NyaXB0aW9uPiA8L3JkZjpSREY+IDwveDp4bXBtZXRhPiA8P3hwYWNrZXQgZW5kPSJyI" +
"j8+I5I0CgAAFcxJREFUeNrs3c9vG1diwHGSkNGF07QqsD0EthEaDRp0L5GPuxdT590mcoGiPbS1FOxhT" +
"7X9F8j6C2Qf9xBI/gsk/wGF6L/A8rHZbaXCdm7dsEAQINaC7Hv2MCvbJCWRHM6bmc8HICj/kEQ9jr58f" +
"BzONAeDQQOA/LQMAYDQAggtAEILILQAQguA0AIILYDQAiC0AEILgNACCC2A0AIgtABCCyC0AAgtgNACC" +
"C0AQgsgtAAILYDQAggtAEILILQAQguA0AIILQBCCyC0AEILgNACCC2A0AIgtABCCyC0AAgtgNACILQAQ" +
"gsgtAAILYDQAggtAEILILQACC2A0AJUxZIhqLdms2kQKK3BYNAZsU13E7uNQguUKqztcFkLH94OQV0ZF" +
"7ZwOQz//jj8cTdcHxc+oYk3CjNaSDywy+GyHbbX9Sk+N8Z2q6jgxsYKrdAaBFKP7Fq47IRtdXmGr9ELn" +
"38vXHaLCK0Xw4Bk9fv97XC1N0tkswlF/Pyd8PV2ivg5hBZINrIhkHfn/AxuvYjYWjqwdGAQSHG5YD3OQ" +
"HP8FhuLWkawRovQkmJk454FT2ddLjjje8Q12xuLeIHM7l1AiqHdzDOy2QQj7sUQZ8yrY25DZ8TndC0dY" +
"EZLJWaz4epogd8yzmoPh3ENlzvhz2vjZsHhaj/8+6OLRNdeB0Bqob2z6O8X497v9w/CHw/GRXY4C8724" +
"z0I/38v7ttrRosZLaUTAnYUtsn2AkPbG0Z0ms8Nn7c6nBFPmtEKrdAaBOq6bDCXUJ8VW0sHQEraZbvBw" +
"xfVzlpGEFpg0bPAGKf4xoG9cPl2kAn/dFDSZ4Xx4DYT31hh6cDSgUFgYUJYY5By332roCWE6+HSs3QAF" +
"BnZeGCY7apFdriEEK7WLB0ARUd2vco/Y5i53hRaoLDlgqpHNtMeO+O1Rltv1mjJeZYXX/g6quJywYift" +
"ddqtf5qxN+b0QK5WqtDZM8itECes7zbNfpxD4UWKMJKjX7W43H/YI225qzRkvOMdlDDnzke4evh8Ahfj" +
"nWA0CK0+Xl9FgehRWgR2nzFA4t3rdECeYa2W/OffzNeCy2Qp8c1f8bYeX1tZl9vlg7IeUZXmzcsTPo1M" +
"6MF8nwgj0e1elj7cTCjNaOFvMVzcg2fRtdsRn8YT2tuRgss4gH9VoxODX/urXgttMAighMPuHIjfLhVo" +
"9nsbvi59y0dYOmAIgLUzk4r3slOA1PF5YKtYWS9YQGhhfzDa+kAIG9CCyC0AEILgNACFGfJEFAWg8Eg7" +
"goU3zN/3Gw2j40IQgsXi2gMaAxpJ3z8cePNqZvbIajtMf//9MfxHUe9xptzNv1P+JzD4dHtIQX2o637B" +
"lDgfrRh21sLl5uNnHZcz46F+jhGN8bXvU1B27nQCm1z0RtdJzsz6kJPQx2+Z1xueBQ+3LXsgNBSudBmy" +
"wJx9ro5bilgwRt+N3uLpOUFhJZyhzYL7N34vvYUD/yczXJjcHdtCQgtpQtt2K7Ww2W7DEfWN8NFaClVa" +
"OMuWOGyU8ajMmWHtbsXD+lny2CeofWGBea5Qd0PV0/Leui7cLvjLPwo7g3h3mSu25YZrRltnWexZrdYO" +
"iD50Gb7wu5U8Syn2QGcb9kdDEsHFKbf798NV3tVPZV0nKGHX5Kn2Vt/YWpCy7SRjbPY7RrM+JdDaA/iX" +
"hTudabejiwdWDqYMrJ1DM+GfW6xdMCiZrJ1nd3tmNliRkuuM9qaR/a0Gw5SgxkteWws6yL741gceIEMM" +
"1rmOqONR9wKVwdG660xibt+rdrPlvPMaIVWaM/aSOKr7kdV3YVrxl+g/VardctIYOmAWTeSPZEd+yC1l" +
"u1LDBMJLWPFiISYdIzERJvhwahtGJj4oGzpwNLBmJlsO74rymz2XLP+bqvVWjUSWDrgohvHtsie+8GqY" +
"/9azGi50IzWXgZTPTDFszXcsBcCZrScyzfffLP5/fffG4iLPWC1w5UXxjCj5ewZ7fPnzzutVuv1bHZ5e" +
"blx+fJlg3T+mUsvjOd1s1rMaJkoRHZz+HGv12uY2V7oQWvZrJaRv1eGgKGvv/76RrjqnP47sb3w7OW2U" +
"UBoGeuDDz7491F/L7YXmtW2nXMMoWWko6Oj5X6//w/j/l1szWoRWmZ06dKltVar9ReT/o/YnntWG8+jZ" +
"h9khJb3fHGe/yS252b5AKHl/VnYef+v2J5r+eALo4DQ8qOXL19eePYltvN74EJoqcfs6+Y0nye2Z45rx" +
"yggtAxnX1OflkVsJxJahJb5BEFsx85oPzMKCC2NFy9ezOUkg2I7UtsQILQ05rm/p9i+bZYlGYSWKm0Ar" +
"VZnnl9PbN97IBNbhJb5E9u3eIcYQmvGlc8LNmILQksmz/OCie1rHVsZQkuuxBaEFrEFoUVsQWhBbEFoE" +
"VsQWgoTT5Ettrnq2soQ2pprNpvPzGxBaKmomsT22D2N0NZcv98v9KntqNj+8MfvqvSMQWgRWksHzV7Rt" +
"+Hd2P7Z0p9XYmwHg8GhLQyhpXH16tUkYlDRZQSzWYSWH3VTuBFVi21RLzQitHiKW6fYdm1dCC3DmdeTl" +
"G5PFWIb908O4yq0CC1vXLlyZT+121SB2IosQst7MzCxne+zhMe2KoSWdyUZhhLHdt8mhdDylpOTkxiGX" +
"oq3rWyxjc8OUtg/GaElMdevX++lPAsrU2xDZB/ZohBaxs3EHqZ8+8oQ2zCGxyG0lg0QWkbL3iXWFduZP" +
"LQlIbRM1O/3t1K/janGNtt3dtdWhNAy0bVr17qNEuwDmmJsQ2QfehEMoaUys9rUYhvXZsPVA1sPQstFZ" +
"rWleAqcSmzDTPae2SxCy4W8evXqXiPR/WpTi22YzXbtaYDQcmHZfrVbZbm9RcU2ewFswxaD0DKVK1euP" +
"EjxGAiJxXbL6WoQWmZycnKyUZYlhHGxzescZPFBqNVqeQGMMzXDxmIU6rwBNJtn/p8XL16shP/3tEw/1" +
"/LycuPy5ct5LhkchjFZ9QIY59hWzGg5W3zHWNhYSrUOmecywnBdVmSxdMC8Y7vbKNGLY3nFNotsnMk6w" +
"y1Cy/xduXLlfqMk+9fmFdtsf1mRRWjJNbYbNY7thmMZMNUDtBfDar4BnOPFsFFevny5E67Wy/SzTvsCW" +
"bZccMvJFplGbKzQCu3Un/vixYv18Pk7VY6tNVmElkJDGz1//rzTarX2YsOqFlu7cDGv0FqjZSbxADQht" +
"DfCh6WZ8Z1nzTb8cjyIP5fIMpcJjRmtGe28vHz58n642izzzNZ6LJYOSDq0UdnWbU/H1noslg4ohfjGh" +
"vi0u4zLCCJLXoSWPGIbj2VbmqfeMbbfffedNyIgtJRsw2q1ynTUr+6HH37oKFwILeXy0UcfHTdKcurt7" +
"EEBhJbyicdGyE5amKy4npw9KIDQUlopH/Grd3JysuUuQmgptWwvhFRnjPvZudFAaCm3ZrP5KMmNv9Uym" +
"0VoqYZXr16l+Ip+19osQktlxKfnqZ1NN9yeR+4ZhJaqeZzSjTk5Odl3lyC0VEpKYYuzay+CIbRUTha2b" +
"gq3pdlsPnGPILRUVRKBCzParrsCoaWS+v1+CoHrXb161cFjEFqqKZ6NIYGbIbIILZVXdOiszyK0VFsCb" +
"8c1o0VoqbZms/ms5qFHaKHaofNCGEKL0ObLmxQQWqpvaWmpyNCazSK0VJ8jZiG0UGGDwcDSAUILeSp6j" +
"weEFhbJWilCCznzFB6hBWB+lgwBi/Yv/7reaDSNA2a0AAgtgNACILQAQgsgtABMZvcuFu7TT/5YyO5dg" +
"3A5+A/jj9BSA//5+yX70VIrlg4AhBZAaAEQWoDieDGMhbPXAUILObPXAXVj6QBAaAGEFgChBRBagMqy1" +
"wEL1280HoVH+Cej/u34v//r5re9bzvTfu2/+9nPtn7yk8tjvm+/a/QpQnMwGBiFOm8AzeT2s2qHy9GUn" +
"xtDuupeJSWxsZYOSM1xuOxO+blbho8UCS0pejRloC0NILRwgSWAi0bTbJZkeTGMVD0cfvDTn/71yqVLl" +
"5ZP/+Mf/vC/hz/88EPv1F/tGjJS5cWwum8AzfQPOvDlr39zEG5l562/HAxWv/rqt5YKSJ4XwwAWQGgBh" +
"BZAaAEQWgChBRBaAIQWQGgBhBYAoQUQWgCEFkBoAYQWAKEFEFoAoQVAaAGEFkBoDQGA0AIILQBCCyC0A" +
"EILgNACCC2A0AIgtABCC4DQAggtgNACILQAQgsgtAAILYDQAggtAEILILQACC2A0AIILQBCCyC0AEILQ" +
"CqhbTabM12C9mAwuBsuB+HjwbuXYC9cr4fL8gW+JoAZbQjocrjcDx8ehThuh0tnTMjXwtVO+L9H/X7/r" +
"rsKENrzRbadzWA3LzBzjjPa7RDbvRhpdxlQNksLjuzTGM4plyrW4tcIH95wtwFmtKNDuzdtZE/FdiXMb" +
"LfdbYDQvh/Z+zGS8/ha4evEF9A67jpAaP8U2fji1505f81Ndx1QFnNbo82Cuh4+vBkuy6f+vjfrksGIW" +
"W0nfN2VcH3oLgRqEdoY2HDZnndQz/iecflAaIHqLx1k+7juLDKymZvuPqDyM9owq4xvKihqLwD71ALVn" +
"9HG5QJDCJDTjDabzbYNIUB+M9qVgm+7F8KAaoc2zGg/K/KGxzcu9Pv9eMCZHcdAAKo6oy1ciG07XOKuZ" +
"UfZcRAAqhPaELhnCQV32QtzQBVntEmtkWbHrwWo1Ix2P8wijw0hwGQzvWEhxHYjXB0YRvjxbeHxOBwfN" +
"8bs+hh+Z56EqzhB6YaPTVSE9lyh7YaNKsZ2J4GNfNd5wyhgu4svxn5xeunqjO2wM/yg3+/H0O6H//9Qd" +
"C0dnBXb3XB1q8hlhPC9D8PtuOfuZIHb3P24e2HjzXE+1qb83Yl7zcRjhRxlp2paMbJmtJM2mP34yJw9u" +
"t9sLPYdY49j7MOlF763e5S8A7uW7eHSnuczqCzWayG4cVu+F7dnoy20jTFR281muEX8Arg3yXP7Gu5Cu" +
"J7nElW2X3iM+a24NGfkLR1AXSL7+uzNMYKL+H7ZIUcPskOQIrRQ+ciuZGdvXvj6afie2/Et5u4FoYWqR" +
"/aggIPav7WUILZCC1WNbFyT3Skysqdjm52PD6GFSoV2p4jlggl27P4ltFClyK6neOyMcLv23DtCC1VZM" +
"kjySHDxDQ7xjRLupfJZMgTwlrsprMtOeCC4Ey4PJr2hITsQflxmiMdd+MvGn86G0ouHNw1/F6/jsRacp" +
"URooZDZ7J2Uj5mRPQjE/Wvvj7j9r4+7ED6cdNyFteHfOdaCpQMoIrTrKc9mT89q3/nz2jTHXXjnWAs7z" +
"lIitLAIt8twI7MzisS36S6HQMbDlO7FaM74NeNs+Kl3o1k6gFGzuxiYzqmDGbWH0cmOKBcvh9mpl/bHr" +
"W1mX2elRD/3nWwGO7cZePa14rvRPmu1Whu2LjNaau7zz3/VyWZzw6fM8Wl/5/TMLntq3MmeHsd3V32bH" +
"Y6wM+JLdsr082c/13JOX9u70cxoqbNr1642/vmf/rHx6ad/uzllRIaHI4yvum8MXwSKM2IHjn8vtg0zW" +
"6GlfrPYxud//8u5zQgbb14Euhdi8qCx2GMolym2z7LxQWipui83/q3xi1/8PI+YvF6TbJRofXbBNsNsf" +
"9/uXzNuZw6YXftZS/K38Xe/+/3TTz75GyEsSDwfnyWEmcZPaIU27dDGF2UWdcBtJrpuVjt9aO11QMob6" +
"JrIJnNf3DEKlg6o2Iw2ezvsURneqVWT0B63Wq3rRsKMlmq5K7JJPSC3HQ93ekJLqrNZT1XTu186RmE6d" +
"u+iiF/YODuKbxyIu1W135k5PYmH9jObTXJW6z4RWkoS2PiOrvUJa8Md79BK9v77zCgILWn/ksajQ22bF" +
"ZWa+05oSVV2gJJ1M1WEFvKZyd6PkTUSleDUN1Oy1wF5RrYTrjaNRDWEZyT/ZxSElvRCK7LV0jUEUz5Ie" +
"WdY7Wcpec5mD4xwpR44u9k28yRc7Tr2wbnHTWiFNp/QOhhMLQKynx08vWc0hJZiQns06wkDKUVEeuF+X" +
"g0XL5QJLQUsHdiw6hOS47Ad3TCzHR9aL4YBsz5Yx3f8bRuJCWNk4mFGa0bLnDg4uBktkHNQ1ozCaEJLX" +
"r90Zjb187EhEFoWq2sIaseBwYWWRWo2m4+NQu3Y60BoWXBo9y0f1O4+f2YUhJbF/+JtGIVa2TcEQsviQ" +
"9sNs9oHRqL64nEQvDtswu+C3R1rH8Pcv4fjHtTCDaEd+yBkRssCnja1WhtmtpW2IbKWDkgjtvfC1erwU" +
"HtUYqYW9zK4FSK7azQsHVDw0sGIX9CVcLndeLPf5YoTNpYusIfZ7nsPHEjmfEsHQiu0yd/GL3/9m4NwK" +
"zvvbL2rX3312+6MvwDtcNW2FZzbobBOF1onZ6TODzLH4erYSJA3a7QAQgsgtAAILYDQAggtAEILILQAQ" +
"guA0AIILQBCCyC0AEILgNACCC2A0AIgtABCCyC0hgBAaAGEFgChBRBaAKEFQGgBhBZAaAEQWgChBUBoA" +
"YQWQGgBEFoAoQUQWgCEFkBoAYQWAKEFEFoAhBZAaAGEFgChBRBaAKEFQGgBhBYAoQUQWgChBUBoAYQWQ" +
"GgBEFoAoQUQWgCEFkBoARBaAKEFEFoAhBZAaAGEFgChBRBaAIQWQGgBhBYAoQUQWgChBUBoAYQWQGgBE" +
"FoAoQVAaAGEFkBoARBaAKEFEFoAhBZAaAEQWgChBRBaAIQWQGgBhBYAoQUQWgChBUBoAYQWAKEFEFoAo" +
"QVAaAGEFkBoARBaAKEFQGgBhBZAaAEQWgChBRBaAIQWQGgBhBYAoQUQWgCEFkBoAYQWAKEFEFoAoQVAa" +
"AGEFgChBRBaAKEFQGgBhBZAaAEQWgChBRBaAIQWQGgBEFoAoQUQWgCEFkBoAYQWAKEFEFoAhBZAaAGEF" +
"gChBRBaAKEFQGgBhBZAaAEQWgChBUBoAYQWQGgBEFoAoQUQWgCEFkBoARBaAKEFEFoAhBZAaAGEFgChB" +
"RBaAKEFQGgBhBYAoQUQWgChBUBoAYQWQGgBEFoAoQVAaAGEFkBoARBaAKEFEFoAhBZAaAGEFgChBRBaA" +
"IQWQGgBhBYAoQUQWgChBUBoAYQWAKEFEFoAoQVAaAGEFkBoARBaAKEFEFoAhBZAaAEQWgChBRBaAIQWQ" +
"GgBhBYAoQUQWgCEFkBoAYQWAKEFEFoAoQVAaAGEFkBoARBaAKEFQGgBhBZAaAEQWgChBRBaAIQWQGgBE" +
"FoAoQUQWgCEFkBoAYQWAKEFEFoAoQVAaAGEFgChBRBaAKEFQGgBhBZAaAEQWgChBUBoAYQWQGgBEFoAo" +
"QUQWgCEFkBoAYQWAKEFEFoAhBZAaAGEFgChBRBaAKEFQGgBhBZAaA0BgNACCC0AQgsgtABCC4DQAggtg" +
"NACILQAQguA0AIILYDQAiC0AEILILQACC2A0AIILQBCCyC0AAgtgNACCC0AQgsgtABCC4DQAggtAKc0B" +
"4OBUQDI0f8LMAASrejggI5pJAAAAABJRU5ErkJggg==\"");

WriteAttribute("alt", Tuple.Create("\r\n                    alt=\"", 26091), Tuple.Create("\"", 26159)
            
            #line 178 "WelcomePage.cshtml"
, Tuple.Create(Tuple.Create("", 26118), Tuple.Create<System.Object, System.Int32>(Resources.WelcomePageImageText_LightBulb
            
            #line default
            #line hidden
, 26118), false)
);

WriteAttribute("title", Tuple.Create(" title=\"", 26160), Tuple.Create("\"", 26209)
            
            #line 178 "WelcomePage.cshtml"
, Tuple.Create(Tuple.Create("", 26168), Tuple.Create<System.Object, System.Int32>(Resources.WelcomePageImageText_LightBulb
            
            #line default
            #line hidden
, 26168), false)
);

WriteLiteral(" width=\"346\"");

WriteLiteral(" height=\"658\"");

WriteLiteral(" /></div>\r\n            <div");

WriteLiteral(" class=\"bottom\"");

WriteLiteral(">\r\n                <img");

WriteLiteral(" src=\"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAABLwAAADKCAYAAACv61n1AAAAGXRFW" +
"HRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAKsZJREFUeNrs3VtsXPed2PEzc87ceBlxJFKKR" +
"6Iskk5sL1U1m6hoyVYdF4VhAoMt7D64LwEmfUqQPGwKC32owTgbgy/BGNuXBA7ysNA2C7RddJ3dxQBFX" +
"TQQ7I4LrNEkgp2E3shkZVqOJVO8Dzn3nj95KFPk3M7M/9zmfD/A0VDkmXPO/M9l5vzm9//9g4qPZfOpa" +
"QUAAAAAAAB9Jejz1/+vOAQAAAAAAAD6i28DXkZ2V0J/nOIwAAAAAAAA6B9+zvA6DHTRrREAAAAAAKCP+" +
"DngNX3sEQAAAAAAAH3AlwGvbD6V1B8Sxn9Ft8YEhwIAAAAAAEB/8GuG13Sb/wMAAAAAAMCjCHgduMyhA" +
"AAAAAAA0B98F/Ayui8mj/16Uv99jMMBAAAAAADA+/yY4TXV5Pd0awQAAAAAAOgDfgx4NQtsTXI4AAAAA" +
"AAAeB8Br/a/BwAAAAAAgIf4KuCVzadaBbVi+t+nOCQAAAAAAAC8zW8ZXtM9/h0AAAAAAAAu57eAV7sML" +
"gJeAAAAAAAAHuebgFc2n0rqD4k2syX0+RIcFgAAAAAAAN6l+ei1Xu1wPpHl9TaHBgDguGuZXN3M/G/dS" +
"AdoNQB+vQZyPQQAOMlPXRonO5zvMocFAAAAAACAd/ki4GV0U0x2OPukPn+MQwMAAAAAAMCb/JLhNW3x/" +
"AAAAAAAAHAJvwS8pkzOP8mhAQAAAAAA4E19H/AyuieS4QUAAAAAAOATfsjw6iZbK5bNp6Y4PAAAAAAAA" +
"LzHDwGvaZufBwAAAAAAAAcR8JL/PAAAAAAAADiorwNeRrfEWJdPT+jPT3CIAAAAAAAAeEu/Z3hNO/x8A" +
"AAAAAAA2IyAV2uXOUQAAAAAAAC8pW8DXkZ3xF67JE7qy4lxmAAAAAAAAHhHP2d4TbtsOQAAAAAAALBBP" +
"we8ZHVHJOAFAAAAAADgIX0Z8DK6IU5KWtwkhwkAAAAAAIB39GuGl8ysrFg2nyLLCwAAAAAAwCP6NeAlO" +
"ytrikMFAAAAAADAG8jwcmZ5AAAAAAAAsEjfBbyM7ocxyYtN6MtNcrgAAAAAAAC4Xz9meFnV/ZDi9QAAA" +
"AAAAB7QjwEvq7ofXuVwAQAAAAAAcL++CngZ3Q4TFi0+qS8/xiEDAAAAAADgbv2W4WV1t0OK1wMAAAAAA" +
"LhcvwW8rO52SMALAAAAAADA5bR+eSFGd0OrR1KkcD0AwPOuZXJ1L2//WzfSAfYiAL9eB7kGAkBn+inDy" +
"47sq1g2nyLLCwAAAAAAwMUIeJk3xWEDAAAAAADgXgS83LseAAAAAAAAdKEvAl42dzNM6OtLcugAAAAAA" +
"AC4U79keNmddUXxegAAAAAAAJfql4CX3XW1rnLoAAAAAAAAuJPnA15G98KEzatN6uuNcfgAAAAAAAC4T" +
"z9keE37bL0AAAAAAABogYCX99YLAAAAAACAFjwd8MrmU6Iro1MjJlK4HgAAAAAAwIW8nuHlZJZVLJtPk" +
"eUFAAAAAADgMl4PeE35fP0AAAAAAAA4xrMBL2OURKczrMjwAgAAAAAAcBkvZ3i5oYZWIptPJTmMAAAAA" +
"AAA3MPLAS+3ZFdRvB4AAAAAAMBFCHj17iqHEQAAAAAAgHt4MuBldCOMuWRzkkY9MQAAAAAAALiAVzO83" +
"JZVRfF6AAAAAAAAl/BqwMttdbMIeAEAAAAAALiE5wJe2XwqoT+4bWRECtcDAAAAAAC4hObBbXZjNlUsm" +
"09NX5+9+T6HVG/SuUw8l76xSUtAlmuZXP347966kQ7QMgCsvM6YZeV16fj2cQ0E4LfrIAB/8mKXxssu3" +
"a4pDicp/k06l5mjGQAAAAAAQLc8FfAyRkN0a/dB6njJ8aI+zdAMAAAAAACgW17L8HJzUCmRzaeSHFLdE" +
"90ZjX1MhhcAAAAAAOia12p4TXpg++5yWHXtMNA1ns5lpnPpG9REA/qcjJofVqCOCACug1wHAQDeRoaXX" +
"Fc5pHoy2+RnAAAAAACAjnkm4JXNp0RR+JjLNzNp1BlDd+aa/AwAAAAAANAxL2V4TbOd/Ut0YdQf4kd+N" +
"WPU9AIAAAAAADCFgJd/t9NtXmzwO7o1AgAAAAAA0zwR8DJGP0x4pE0nOay60ii4RbdGAAAAAABgmlcyv" +
"LwURIpl8ymyvExI5zLjSuPMOAJeAAAAAADANK8EvLw2+uEUh5YpM01+HzdqewEAAAAAAHTM9QEvY9TDp" +
"MfalSCNOXNd/g0AAAAAAOAEL2R4eTF4lDDqjqEzrYrTE/ACAAAAAACmEPCyDsXrO5DOZURAK95q/xs1v" +
"gAAAAAAADrihYCXVwNHVzm8OjIjaR4AAAAAAIB9mps3zhjtMObRtk2K+mPXZ2/ucpi1NNfhPP+VpgIAu" +
"Mm1TO4Z/SFDSwDw8XXwkv7wCi0BwI00l2+f10c7FAG7dznMGjO6KnbSXXGW1kKbD1t1WfO/dSMdoEUBt" +
"LmGPGPc4D3jxetgu3m5DgLo4DpyybgOfp3WAOBWbg94eX20QwJerXVakD6ezmVmc+kbeZoMAODgDd4zi" +
"ssCXQBg83VwRH/4jj79sT6N0CIA3My1AS9jlMOEx9uXwvWtmRmB8Tl9IuAFAHDiBu8ZhUAXAK6F31MId" +
"AHwEDdneE33QfvGRB2y67M33+dQe1Q6lxEjM5opRj+nUB8AAGDvzd0zCoEuAFwLv25cCy/RGgC8hICX9" +
"UQdMgJeJ5mtyzUuan7l0jc+oukAeOgmoe70NlCPqav99oxCoAvoi+sh18Cer4V/phDoAuBRQTduVDafE" +
"l0Zk33SxtMcZg3N2fQcAADM3OD9XH8Q0zO0BgCuhQS7AHhX0KXbNdVHbZww6pHhUTM2PQcAADOeoQkAg" +
"GshAO9za8Cr37KiKF5/RDqXEft3vIunzhm1vwAAAAAAAJoi4GWPqxxqj+ila+IszQcAAAAAAFpxXcBLj" +
"GrYh+2c1F9XjMPtoTmHngsAAAAAAHzAjRle/VrkneL1yn53xniPbUEdLwAAAAAA0BIBL16X3XrN0Bo3a" +
"oABAAAAAAA05KqAlzGaYb92/aNw/QEZXRKp4wUAAAAAAJrSXLY9/VzcPSbqk12fvfm+z485GcGqF/XpJ" +
"5y+/eVaJlfvh+1460Y6wN4E4OVrYS/bwDUQAAC4hdu6NPZ7FtSUnw+2dC4jgl1xCYuaNmqBAQAAAAAAn" +
"OCagFc2n0roD8k+b2+/1556TuKyGK0RAAAAAAA05KYMLz8EgxJGnTK/mnXpsgAAAAAAQB9xU8DLL939f" +
"Fm8Pp3LjCtyg5pkeAEAAAAAgIZcUbQ+m0+JkRn90t1PFOZ/24fHmuwAVTydy0zn0jfe5zSG38gsak2Ba" +
"QBcB7kOAgDQj9yS4eWn2lZJI8DnNzMWLPNFTmEAAAAAAHCcWwJefuvm58fi9VZ0QaSOFwAAAAAAOEFzy" +
"Xb4LQAkXu+7fnmx6VzGqnpb06I2WC594yNOZXdq1eWELiQAAAAAAKs4nuGVzadEsXq/dfHzW0ablQXmZ" +
"ziNAQAAAADAUW7o0ujH7n2xbD5l3etemB/Qp6dc9HqtDEo5Nlrj4vLElJi4jAAAAAAA4C5u6NI47dO2F" +
"4ESq0YY/Io+Pa5Pv3X6RYqRFPWHcQtXMeeCY/c2lxIA8B6ZI/0BANdBAHAXRzO8svlUQn9I+LTtrQz0f" +
"VU5CHq5geWF5S2sEdbJPvRrwBYAAAAAANdyukujn4MFiWw+lbRo2aI746iyMH/RBa/TjmCU7XW8FpcnD" +
"oO1CeNnAAAAAADgEk4HvC77vP3lF69fmBeZXQPG/xyt45XOZeKKPcEoJzK8ppv8DAAAAAAAHOZYwCubT" +
"4mRGSd93v5XLVjm00d+vubw67MrEDWezmXGbX5tl5v8DAAAAAAAHOZkhhdZMYqSNAJ/Mh2t3XVxf8RG5" +
"8zauC7bsrwWlyeOB2snjd8BAAAAAAAXIODlPHntcFCza/TYb50sXj/Xp+ua5ngGAAAAAMC9nAx4TdL8+" +
"2QGShrV7PqqEy8qncuI1xW3cZUzRs0wp45djmcAAAAAAFzCkYBXNp8SwRC6gB2QGShpVLPLqQyvFx1Yp" +
"11dKMnwAgAAAADAxZzK8Jqi6R+KGQHA3hzU6rrY5G9OBL1mHVin5d0aF5cnxLHbKFgbM/4GAAAAAAAc5" +
"lTAi2yYR8kIlLQKatnardEYMdGJfTzn8LHLcQ0AAAAAgAtodq8wm08l9YcETf8IESj5mx6X0Sqo9ZTNr" +
"2fGoXaMi9phufSN9y3eV1buRwAucy2TG9EfvqNPf0xrAPDpdfB5/eFPaQkAgJc4keFFce+TEkYgsBetg" +
"lqjxgiOdplzsC0tW/fi8oQI1LYK1iaMeQD0xw3eiD59T/9xSZ9e0acRWgWAz66Dl/Tp5/qPb+jTJVoEA" +
"OAlTgS8rtLsDXUfCDyo0TXQZi47uzXOOtiOVgbbpiXNA8D9N3nfUwh0AfD3dfBPjevgM7QGAMCLbA14Z" +
"fMpkf2SpNkb6iUQ+HQH89hSuD6dy4iAU9zBdpzWt8Gq9V+WNA8A9yPQBcDvvkMTAAC8zO4ML0axay6Zz" +
"adiXT63k2DWRWVhftSG1zHjgraUnuW1uDwh9k0nWXiTxrwAAAAAAMAhdge86O4lu30OanN1Gsiyo3j9n" +
"Avacc7hfcNxDgAAAACAgwh4uUs37WMmiGVpHa90LjOuP4y7oB2tqCE2adG8AAAAAABAMtsCXtl8imBXe" +
"9200TUT81pdx2vOJe0YT+cysw7uG451AAAAAAAcZGeGF0GADpgKDC7Mi5EZL5pawcGIjlaZcVFTPidrQ" +
"YvLE6L2nJm6XDHjOQAAAAAAwAGajesiANAZEfB6v8N5uwleiW6N/1f2RhsjI865qB3FtrwicZ9085zbH" +
"M7+cy2Tq9MKALgGAgAAOMuWDK9sPpXUHxI0d0fMBAa7qcllVeH6WZe147hRU0yGaZueAwAAAAAAJLCrS" +
"yM3/51LGAHCTnQTvBo1RnaUbc6FbdnzNi0uT4hAbTfB2oTxXAAAAAAAYDMCXu7Uvr0OanENdLl8K0Zrn" +
"HFhO844fOxy3AMAAAAA4ADLA17ZfEpkuSRpalM6CZQ83cPypRauT+cyYnvHXdiOMrLOLjv0XAAAAAAA0" +
"CU7MrzIcjEvaQQKW+klaHVRWZgflbi9c25tyHQu0/W2LS5PiJEZJ3tY/aSxDAAAAAAAYCM7Al6Mzii73" +
"Q5qcPUasJJZvH7Oxe3Yy7bJCNYS8AUAAAAAwGaWBryy+VSMG/6utWo3GcEqKXW80rlM3OX7uJc6XpMS1" +
"j/JoQwAAAAAgL2szvDiZr97rYJI1yQsX1YdrzmXt+O4UWNM9j6wcxkAAAAAAMAEqwNe3Oz3IJtPnWy/h" +
"XkxMuNFKSs4GOmxV7MeaErT27i4PCG6lMqovxUzlgUAAAAAAGxCwMvdGrWfzBEWZXRrnPNAO845fOxyH" +
"gAAAAAAYCPLAl7ZfCqpyMmQ8bNGmUFflbj8nmqBpXMZkTkV90A7zhi1xswg4AUAAAAAgEdZmeF1lebtW" +
"cIIHB4lc3TFUWPEx24956G27DjLa3F5IiHaXuZ+NJYJAAAAAABsYGXAi6wW2e14UHNrQPLye8kYm/VQO" +
"846fOxyPgAAAAAAYBPNioVm8ynZGTJ+JgIlbxo/P23B8kUQ7Q2zT0rnMuOKt4I4Zup4XbZg/WKZb3M4w" +
"4uuZXJ1WgEA10EAAOAlVmV4kc0iT9IIIApfsWD5F5WF+dEunjfnsXaMp3OZtsfl4vKEqDs3acH6J41lA" +
"wAAAAAAi2kWLfcyTSvVlLIwf08RNbesIeqCmc0+mvFgO76oT6+0mcfKYK1Y9rtuaIhsPnVOORgUQQT3z" +
"hnTUTv6dNt4vHV99uZtTkMAAACg6efrIeOz9RV9Ovz5uFuHn7P1z9e3aDXAWpoFJ7pVGTJ+JgIlpy1cv" +
"qjjZTbgNefBduykjpeVx65YtmMBL/3cFAGuZ5WDYOW5Dp4yc+S54o05r0/v6G/OeU5JAAAA+J3xJfKs8" +
"Rm7k/uIK0eeKx7eOfIZe5sWBeSyIsOL7ozWtOkTFi7fVFfJdC4z59V2FLXHcukbHzl0/DpybuhvpuKN9" +
"WtH32C7MGi8kT9rBL9E3bef8cYMAAAAvzE+X7+g9N7rZcaYdvRl8vkakMyKGl5kd0lWKGvaYKhsbbDkY" +
"ARIMxdmr2q67YvLEyIDyso6WzFjHXa9EU/p0w/0H8V0ReKiRfBLBNBu6Mt/gTMUAAAAfiAyuo58vpZ5T" +
"3T08/XXjO6RAHpkRcCLDC/Jfr16ZjSmVYYtXs1XTcw75+HmnHP42LXl/BBvlPrDDxW5ga5Gb8zf0Nf1I" +
"6O7JAAAANCXjC96f2TD5+v9z/F8vgZ6F5R8ERA384xEJ9nSenw0rFYHLF7NU53MZIx0OO7h5mxVx8vzA" +
"S/xbZAIQBlvlHYRWZ0/0Nf7LGcrAAAA+onx+VoMfPUN5SAgZQdRG+yHfL4GeiM7w4sotAXuFwZG1EA9F" +
"FGrUQtXM6oszF/sYL5ZjzdnvFENssXliYT+kLBh/QljXVa8GYvz74biTLdi8eb/Em/KAAAA6BdG10LZ3" +
"RfNEJ+vX2JPAN2RHfCiO6Nk790fHS3XgvuDC7ikW+NcHzTrjMPHrvR1GcEu8WY86HDbEvQCAACA5x0Jd" +
"jldo/pZgl5Ad4ISLwhJxZ4MGV9Z2RoaOfw5qlWsLl7YsnB9OpeJK94uWH+oUdDuso3rl7quI2/Ggy5pX" +
"4JeAAAA8CwXBbsOiaDXN9kzgDkyM7wYndECH20Njx7+HArWolqwFrJwdReVhfnRFn+f65NmHU/nMg/rk" +
"C0uT8RsPn4njXXK4qZg16GXKLQJAAAAj3rJhfe3z/OlMmCOzIDXVZpTrpWtoaFCWXukbldUqzhZvH62j" +
"5r3aPDOia64UtZpfNPj1mDzd7VQmRMZAAAAnmGMxujWXi3f1LfvHHsJ6IyUgJd+0olslSTNKdcHDxIns" +
"q0cruM110fN63TAa1LCeSeGRH7exW187vGnf8mJDAAAAE8wgklfc/Em7g8UxZ4COiMrw4ti9Ra4szl8I" +
"uAVVatWB7wa1vFK5zJiH8f7qHlnjJpkghMZUjLOGdf34x+7sKzEz9znZAYAAIAXiM/Xgy7fxivZfGqWX" +
"QW0R8DLpVZ3o9GNYqRhkfrBUNnaoNfCfKOg11wfNvPs4vKEOHZjDqw7pq+76xpXRv99T9TNu/DF9zmhA" +
"QAA4GpG7wmvDND1DfYY0J6sgBcF6yVb2jg10uxvDnVr7MeAl3hNThZW7yVQ/IJXGjl++r4yGF/npAYAA" +
"ICbveChbT1HAXugvZ4DXvqJ5lSGTF9bWo83HS0xrFZtLVxvjGjYj1l8Mw6/rukuzzkRpPNUkPkLl/6ek" +
"xoAAACuZNTumvHYZhPwAtqQkeFFd0YL3N0eahrwUgP1UEStRi1c/aiyMH/xyP9n+rGNR0LF8fVyxMnAU" +
"WJxeSLRxfOe91pbnz73MSc1AAAA3MqLNbGuMGIj0JomYRlTNKNc790fHW03j+jWWKyqexZuhujWeMf4u" +
"R+7Mypj4V3ls1JsfCRUXHNwM0TA+G2zb25ubtfdihb8/c5gZH0vEnqw/vk4B4FzK8rug1ElWo5ykgMAA" +
"MB5C/OiZvLk//74d/+6UgueOfz1xfhWIapWao8N7RRd/gpEoO4NdiTQWE8Br2w+ldQfEjSjXLfXT7UNe" +
"EW1ypBSjFg5/N1Xjlw8+3IUkEsDm8pmJSy6a95ycDMuKyYCXkZ3Rtd9k7O2Fw393SdfGPl4eyi2uhuNP" +
"LzAFD8PbpWHPlVK2pai1lRlsDSgPP3tP//F6PaZf/vWjfQvOesBAABgi4V58Vn6WeMeZzIYqAff+Tj5S" +
"BKH/rn29MN7hlOb21Mj6zt/eO7epgtfzRWFgBfQVK8ZXnRntMC9wsBIu3lCwVpUC9ZClVqwbNFmXNTfD" +
"EbTX77zJf3neL+1sd5+okujUqypiVJNDYeD1ZJDmzK5uDwRe/LS0m6n87upHT/ZHoz8rzsXx/THtnX8g" +
"mp1/7EarCqb0S0xffnB0NovLrz0oz9Zee1b3+PMB+Bn1zK5P9Mf/h0tAQAWOQh0fU05VvtKvy+ItHra8" +
"kZ8SExvrZwf+4dn76+nxldWXfSqrrBjgRb3oD0+n4CXZCtbQ0OFstZRn6+oVrGjeP1z/djO56PbD3++V" +
"xoYd3hzzJxHrsnu+h9Ll8b+4tdPX+wk2CWoWuXE70pqWdmJFF5J/IfsL/ZCe1wAAPjZ1/Xp5zQDAFhgY" +
"V4Eum4oDQq9twt4PfzcWlWDIvPr9V9eubS0ccotg7YNZvOpIXYw0FjXGV76iSW6MiZpQrk+eJAY7XReU" +
"cdruxTesHBzRB2vvqzflYzuPPx5rRy5cCG6ddvBzRFZW+92OK/j3+KIGl3/+TdPXTjadbFTgUBdqdcDj" +
"f705d+dXVIurCWVkcIpLgQAWrqWydX79KV9mb0LwMfXQPkOanR9t9Vn6EBAUc0sUr//Cv23xS9e+GcXP" +
"r7/T5KfrLvgVYp7iVvsbOCkXro0UqzeAnc2hzsOeEXV6rClB0ew9k/1h/F+bOez4cLDnwtVzemsKc9kS" +
"ooujH+5+KUL4huubp4vujVWK80vOyuJu/uPBL0AAADQk4Ng1w+UNiVBwmq1q2ytt1fOj90vDET+6Inbn" +
"9LYgDv10qWR7oySre5GoxvFiKmU1MFQ2bKgVzRUHVvfifRdO4vujKKG16FaPRD+rBRzMugVW1yecH0AW" +
"WR2/fXvph7rNtjVKRH0Wh/Y4IIAAACA7nQY7OrV4oNE/OZHF87Q4IA7dXXjms2nRBScgJdkSxunRsw+R" +
"3RrtGp7QlotsV4I9107j0VO1odfLUW9VMfLEX/1wReTIoXbjnWJoBc1vQAAANCllxSbBnsSdb1+s3qaO" +
"lqAC3WbqTFJ08m3tB4fNfucsFq1pHB9MFDXwmrt7NZuqO/a+Wj9rkM71RDdGlsQ31x1WpxeljtnVvZHd" +
"AQAAAA6tjAvCtPP2LnKN5cfPyd6Q9D4gLt0e1KS3WWBu9tDpgNeaqAeiqjVqOxtiYSqp8VjsaIqhZLWN" +
"208Eioqg2r5xO+LNTWxUw05+c1MYnF5IuHGNlvbi4Z+dW9sRMaymhSsb0iM4Lg6tMaFAQAAAJ056Mr4T" +
"TNPqdYC5V5XK0p+/M/lx8fYAYC7EPByiffuj452+1wrujVGtNrDC3Y/1fEaC+82/dv9YuyCw5vXyXlle" +
"1HMt1fOn5ZVt6tWNTUIjrI6+IAsLwAAAHTqeX0aNPOEaj1YkbFiUc9LfFHswGveYbcDjZm+ic3mU0n9I" +
"UbTyXV7/VTXAa+oVpGemRRSaw+zjdZ3+qeO16WBzaZ/26qGne7WeLmDeWwNeInU7KWNuJTjq14zHzMTw" +
"S4K2AMAAKBDz5r+vFnvPcPr0N998oURu1/w9dmbt9ntQGPd9FW7SrPJd68w0PXFMRSsRbVgLVSpBaVcr" +
"MNqbTgYqD8MaooujaWKqoQ1b2faiJEZRZfGZrYrIacL108uLk/Enry0tNtinlt2btBvV08POZXddWhtY" +
"EM5s32aiwTQpWuZXJ1WAMA1EH1vYX5W/9f0F9jlarAoaxM+3IiL7LL7Nr7qD9nxQHPd3MhSsF6yla2ho" +
"UJZ66kOV1SrSCteH9aqJ2pJ9UPx+vPR7bbzfFIcdPtojba+qd1eHxmUtaxqtbtjSIzWWFbLXCgAAADQy" +
"pVunlSuBYv1eqAmYwPEiOafbA9aVg+mVg8Ei1U1djjd2RxeVRbmr7DrgcZMZXhl8ykRCEnSbHJ98CAx2" +
"usyRB0v/QIrpe9XNFQ9sY/XCmHlzPCep9u50eiMx22Ww+cei+x85OBmioDyu83+eH325rZ+Hn6o2BR4/" +
"mw3Ku0Nu1rpfvCD3dCeEqqGuFgAAACg1eforhSrwe2oVo3L2Ij/txmPPTa0Iy1rTAS59irqUKGijVRqw" +
"Uc+m7+5/Pi/0B/+kbIwL/77jj69obz86i0OBeCA2TtQitVb4M7mcM8Br6halVK4Phioa2qwfmJZ/VC4/" +
"my40HaerUpYZHi96+BmdnKOvalP37BjY8S3VDKWI+p3ddulUdgLF5X43jAXCwvQ1QMA10Gug0Cf6DrTa" +
"a+q7sgKeG0WI9K+pd2raEMbpdC5ej1womdWqarWfrN6+mgXlpn9aWFeBLx+rLz8KrW94HtmuzRO0WRyr" +
"e5GoxvFiJSi4IOhcs8RgVioerbZ37wc9BLdGUUNr3bK9eDgejmScHBTY4vLE+3Oszft2BCZ6djlUk89d" +
"pVqgJEaAQAAYI29irYtq3j9/d2YlM/Q68XIufVi+LFGwS5haSPerF6LCPz9UFmYf5Y9C7/rOOCVzadEE" +
"XMyvCRb2jglbSQP0a2x12WEtFrTYM96wbujNY5Fdjt/cylHnB6tseV5Jro1KjYEvfaqWk/F6gP1wH4Gq" +
"f4mrVRKvR07oo4XAAAAYNln34q25ZZtEcGuvYraMuPs7ZXzD9os5iWCXvA7Mze0BLsssLQeH5W1rLBaH" +
"ZCwjKYZXl4uXN9J/a5DG5WI2wvXCz91b2sHgsFK6IxailwU/6uUovtBLwAAAMCtdsramqzi9b3YKIbH2" +
"gW7Fh8kNtf2op1kpL1EUXv4mZmAF6MzWuDu9pC0gJcaqIciarXrvmORUDURCDSv61asqEqhpHmujUdCR" +
"WXQxCh/hap2rlRTnUxnSywuT7TsVnl99uan+sPPrNyIqFox/YYfrGqntGLkYrCqnhL/F4GucrH3rO7B0" +
"iAXCwAAAFimVg/UdsraqpPbIEZe3K1oLXsAidpdHWR3HfWKsjA/xB6GH5Hh5aD37o+Oyl5mL90ao1rz7" +
"K5DXqzjNRbeNf2ce6UBr2R5fWrVBpgZXSZQC8a0UuRisKKdOXpdKe4Okt0FAAAAT9guh9YrtWBPIyxeG" +
"N7a7fa5W6XQWLt5fnVvbL3D7K5D4pvj59m78KOOAl7ZfEoU0Y7RXHLdXj8lPeAV1SpdR+9Daq1tsfb1H" +
"e/V8bo0sGn6OZuVkNN1vK62m8Go5fWalRsxFC61fDMVdbrUcjipT48pRs2uQ6JuV7UspxtstBThggEAA" +
"IBWbslYyEYx/GkvXRsjarWr0ZZEdlelFmz5ofeT7cHdmx9d6CYL7QUOD/hRpxleZHdZ4F5hYET2MkPBW" +
"lQL1kxHGfTnxNRgvW12mOjSWKqonmljMTKj6NJo1lYlfMHhTU8uLk+0DTJfn715MOywRc4P7TT5hioQV" +
"MuhMVGnK1ALnuhGW6uqSmlvQNp2DJYGuGAAAACglQ9lLKRcCxa3yqH73T7/8fhmVxleuxWtZd0u0ZXxr" +
"z744t1uP04rC/OzHCLwGwJeDlnZGhoqlLWoFcuOahXT0YGI1j6765CXitefj2539bxaPRBeL0cSDm9+R" +
"+fd9dmbbygWjdrYKCU7WNESok5XoKY2DJCKLox7O8PSujJGy1FFralcNAAAANDKLVkL0u/TNrdL5oNeo" +
"neEmbIgR1VqgabZXSLY9ZeLX1rZrWi9FNWnJjd8p23AK5tPiZv+BE0l1wcPEqNWLbubOl7hUHWs03nXC" +
"t7p1mhmdMbjPivFvFDHa9/12Zuia6P0oNdTZx5sh9Xq/htroKYO7tfpqmqJZtcO2cEuIVE4xQUDAAAAr" +
"b38al6RWN9W1PParWjrZp7z9JkHW92ur1l3xsNg1yfbg8UeXxKjNcJ3OsnwIrvLAnc2hy0LeEXVqvmAl" +
"1o72+m8XipcfzZc6Pq5m5Ww0wEvU9/CGEEvqSM3xrRK7crptb2DOl2hc8frdB0lujHubsf3H2URmV0jB" +
"LwAAADQGalfAG8Uw/c3S+GOg2hXxj7blLl+icEuwJc6CXhdpZnkWt2NRjeKEUuHhh0MlTsOesXClbNml" +
"++FoJfozihqeHWrWFMTO9WQk0P4xhaXJ0wFnK/P3nxdOShkvyNrI6aC6mV9b7fsfiuK0+9ndtWCUhvgz" +
"M5pujMCAACgUz+T+TlYEN0b1/YiK+0K2V8Z+2w9Ed0ry1qvKFD/k1/9gyWCXUD3Wt6dZvMpUTQ7STPJt" +
"bRxasTqdZjp1hhWa6a7rK57oFvjWGS352WslaNOj9Y4ZfYJ12dvim+2vqVIqmMQDtaUyyONs7P3uzAWh" +
"vYnmd0Y99dbDSlnN0e5YAAAAKAzL79qySjmxaq6e383uqQ/bje+n6rWro2vrMpYl8jqenvl/P2/+PXTv" +
"dbsAnyvXToG3RktsLQet/wuXr/odly4PqzVxswu3wuF63up33VorRxxerTGrs7B67M3P9Wnf6//+H1FQ" +
"i2DJ+Pbytno518uieBWuRhTdrdO7Wd3WeHi6gUuFgAAADDnoJaX9Nq2tXqgtrYX+URke5VrwUe+Wf+jJ" +
"z68K0qB9LJ8NVAvLz5IbP6n95++83/uPrZuQct8yMEBvyHg5YC720OWB7z0C2YoolbbjgIZVmvDwUA9Z" +
"nb5xYqqFEqaa9t4JFRUBtXeM4oLVc3pDK/E4vJE11mW12dv5vUpoxx80/VOLxty7ewD5ZRWfRjoKu1Fp" +
"Wd1HbqwltwfnREAAADowo8ViwI8IttrdTe6IgJfIuPrXz5+59OJUxu9dC0R39L/7M/f/4P/8re/m/p0b" +
"S9atqhNbnFYwG/aRSwYulSy9+6P2tZHS3Rr1C/Ce63mCWvVrkfgFHW8BsIVV7bzWHhXynJq9UD4k+Lg+" +
"GORnY8cfDniPLzbywKMbo5vZvMpEcATI7TMGsttG9DbfDCmbK6eVdY+TSqntoeVB6N3lHpoz7IXK4JdF" +
"KoHAABA10TXxoV50dvhB1bd04rAlz795A/P3RN1w2aMz9hXOvl8rRwEn0RATnw5fRCIWvjn4vP5P7aoR" +
"XYUAl7woabpGfqNscjuytBEcv313089tbwR/4Id6yrXgnu/3xlcajXPmcHiVa2LGl6CCHb9wYU1V7bzs" +
"2N39rO8ZDgd2vvtk0Nr7zr4cu4+eWnpP1q1cP1c/1GTDwI/1d+Af3otk6sf/WU1WFWWRu8oe5KDXqI4/" +
"WMb5wh2AQAA+NBbN9Lyuw4szIsBqF5SDgJSsr2mvPzqm00+X4tA25UGf/q+6IHRYntvKJ0FzMx6U9/W1" +
"zjK4DetujRO0Tzy3SsMjNi1rlCwFtWCtaYFloKButZtsEsQXRpLFfeNoCdGZpQV7BK2KuFxh19ScnF5I" +
"mbh8rfNzCwCU0/cm1DObrUu/VbV98PRqR6oN513sDigTHx2kWAXAAAA5BGZXi+/+ifKQRfHVgV+h45Nr" +
"UboEplZ324W7Orxc/ePLWiFHYuWC7heq4AX9bskW9kaGiqUNVsLE0W1StPi9ZFQ9XSvy3dj8frz0W2py" +
"yvXg4M71dCQwy/LdeejGEHxyd8/oSSaBKlEBtjRqaKe7P4qRmIUXRgnPnucml0AAACwxsuvvqEcjGLeL" +
"Eg1eWxqlBQgBoISWV3f0qfbFm2nyP56R/JSXzdGrwR8p2ENr2w+lWxykqMHHzxIjNq9TlHHa7sU3mj0t" +
"0gXozMet1YIK2eG91zVzjJGZzzufjF2YXCg/FsHX5YIeL3rtmM6VA0p59eSytnNMWUztqWsDWy07eoog" +
"lwio2t4d1iJ7w1zYQAAAID1Xn71IGC1MC+ynZ5VPq+71Yq4sTgIQh0Eo+wguh7Kqj32ZpeZaEBf0FrcX" +
"EOyO5vDtge8omq1aUQhrFbP9rp8Ubjebc6GC9KXuVUNi770Tga8XD2AhAh8ndk+vT/tfzKIFJT3zv/mk" +
"XlGdk7tZ3OJeQEAAABHHGQ7vWFMom6WCHr992NziSDRa0aQzP7tk1Nw/2f6sl5nh8PPmnVpJOAl2epuN" +
"LpRjDjSLW4wVD4R9AqrteFAoO0onR1xU9BLdGcUNbxk266Exks1NezgS4stLk945rwUGVwnjrlqmGAXA" +
"AAA3OXlVxuNXvipI8Guz7dpe7/rpKL8tMFfxT3JuSPTyW1XlO8T7AIaBLyy+ZToypikaeRa2jg14tS6R" +
"bfG47+LhnrP7jq0Xgi7pp3HIruWLXu1HD3n8MtjIAkAAADAL15+VQS8MorI1vq86H6zgJcopi+6a37bx" +
"u6XgKtp3FTbY2k9PurUusNq9US6TVirjslavpsK11tRv+vQWjky/lhk5yMHX57I8PobziYAAADAJw4yz" +
"V7fnxbmxb26qD/23SNzfF+fbjuakQa4VLDJTTUku7s95FjASw3UQxG1+nAIvGCgrqnBurRq4cWKqhRKm" +
"uNtPBIqKoNq2bLlFyohpzO8EovLE2RfAgAAAH50MDrkrWO/yxPsAhoj4GWD9+6Pjjq9DUe7NcYkdmc85" +
"IY6XmPhXUuXX64HB9fLEadHL53kjAIAAAAAoLVHAl7ZfIpglwVur59yPOAV1SoPC+aHQ/K6Mx5a33G+j" +
"telgU3L1/FZKTbu8Mu8yhkFAAAAAEBrxzO8CHhZ4F5hYMTpbQgFa1EtWAsZP5+WvXzRpbFUUZ18fftdG" +
"q22WQk7HfBKLi5PxDirAAAAAABo7njAi4L1kq1sDQ0VylrUDdsS1SoDkVA1EQgolhTccrJ4/fnoti3rK" +
"dbURKmmOp3ORmAaAAAAAIAWHga8svmUKIadoEnk+uBBYtQt2yLqeEU1+fW7Dq0VnIsDWTk643H3SgNOZ" +
"3kR8AIAAAAAoIWjGV7UBrLAnc1h1wS8omp1OKzVxqxavihcX60FHHltZ8MF29a16fxojRSuBwAAAACgh" +
"f8vwABfcA5F9k0oGQAAAABJRU5ErkJggg==\"");

WriteAttribute("alt", Tuple.Create("\r\n                    alt=\"", 41057), Tuple.Create("\"", 41123)
            
            #line 181 "WelcomePage.cshtml"
, Tuple.Create(Tuple.Create("", 41084), Tuple.Create<System.Object, System.Int32>(Resources.WelcomePageImageText_Skyline
            
            #line default
            #line hidden
, 41084), false)
);

WriteAttribute("title", Tuple.Create(" title=\"", 41124), Tuple.Create("\"", 41171)
            
            #line 181 "WelcomePage.cshtml"
, Tuple.Create(Tuple.Create("", 41132), Tuple.Create<System.Object, System.Int32>(Resources.WelcomePageImageText_Skyline
            
            #line default
            #line hidden
, 41132), false)
);

WriteLiteral(" width=\"1212\"");

WriteLiteral(" height=\"202\"");

WriteLiteral(" /></div>\r\n        </div>\r\n    </div>\r\n\r\n    <div");

WriteLiteral(" class=\"content\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"bodyHeadline\"");

WriteLiteral(">");

            
            #line 186 "WelcomePage.cshtml"
                             Write(Resources.WelcomeHeader);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n        <div");

WriteLiteral(" class=\"bodyContent\"");

WriteLiteral(">");

            
            #line 187 "WelcomePage.cshtml"
                            Write(Resources.WelcomeStarted);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n        <a");

WriteLiteral(" class=\"bodyCTA\"");

WriteLiteral(" href=\"http://go.microsoft.com/fwlink/?LinkID=313397&amp;clcid=0x409\"");

WriteLiteral(">");

            
            #line 188 "WelcomePage.cshtml"
                                                                                           Write(Resources.WelcomeLearnOwin);

            
            #line default
            #line hidden
WriteLiteral("\r\n            <div>\r\n                <img");

WriteLiteral(" src=\"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADoAAAAdCAYAAAD7En+mAAAAGXRFW" +
"HRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAyRpVFh0WE1MOmNvbS5hZG9iZS54bXAAAAAAA" +
"Dw/eHBhY2tldCBiZWdpbj0i77u/IiBpZD0iVzVNME1wQ2VoaUh6cmVTek5UY3prYzlkIj8+IDx4Onhtc" +
"G1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IkFkb2JlIFhNUCBDb3JlIDUuMy1jM" +
"DExIDY2LjE0NTY2MSwgMjAxMi8wMi8wNi0xNDo1NjoyNyAgICAgICAgIj4gPHJkZjpSREYgeG1sbnM6c" +
"mRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4gPHJkZjpEZXNjc" +
"mlwdGlvbiByZGY6YWJvdXQ9IiIgeG1sbnM6eG1wPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvI" +
"iB4bWxuczp4bXBNTT0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wL21tLyIgeG1sbnM6c3RSZWY9I" +
"mh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9zVHlwZS9SZXNvdXJjZVJlZiMiIHhtcDpDcmVhdG9yV" +
"G9vbD0iQWRvYmUgUGhvdG9zaG9wIENTNiAoTWFjaW50b3NoKSIgeG1wTU06SW5zdGFuY2VJRD0ieG1wL" +
"mlpZDozMjVCMDEwM0FBQkExMUUyQjdGNEEwODg0RjhFODY4OCIgeG1wTU06RG9jdW1lbnRJRD0ieG1wL" +
"mRpZDozMjVCMDEwNEFBQkExMUUyQjdGNEEwODg0RjhFODY4OCI+IDx4bXBNTTpEZXJpdmVkRnJvbSBzd" +
"FJlZjppbnN0YW5jZUlEPSJ4bXAuaWlkOjMyNUIwMTAxQUFCQTExRTJCN0Y0QTA4ODRGOEU4Njg4IiBzd" +
"FJlZjpkb2N1bWVudElEPSJ4bXAuZGlkOjMyNUIwMTAyQUFCQTExRTJCN0Y0QTA4ODRGOEU4Njg4Ii8+I" +
"DwvcmRmOkRlc2NyaXB0aW9uPiA8L3JkZjpSREY+IDwveDp4bXBtZXRhPiA8P3hwYWNrZXQgZW5kPSJyI" +
"j8+I1MZRAAAA4FJREFUeNq8md1x2kAQx3UaCoAKAg0YkgYQHTgV2KoAeMqjncfkBbsCSAd0AK5AOA1Y6" +
"YAOyJ7mf5rV6T4l8M3c2ALd/fZ/u/exh0gCy+VyyeiPrHPtqzPVd6p7IcTJ0rbxTO8FMe++/vIy/xY/T" +
"iF9CY+4If1ZUV1SHQb0V1L9Q/WFxJy7CCVxnZkk+hwtlIyTsCcGk53sMZJ8FGcY8Ux7NydB+xihJLI3k" +
"8Tug4TCi1uq92zEfpJxu4DwfoShY3y0o3a5Tyi82GKS0buA8G4xqV3uFAqRB4xYAoHPSURBH08IvwosR" +
"9omFCIbTDI0iok+GkxdrC5UjuqjHnpdCry7xaOcs2uLkQ2mLfQCBTeY1Ne6JRRzcoPH731EWsQuqM+jY" +
"U7WzD4iLWIX1GfFTLVwU+HaG4gQ3WExSRhcDzcVrldhYl63mAJCnwEtybiJx0tjNvETtCk9c/YDq2OuF" +
"jUSWjPJuInHSy0mtSk9c7ZmSvEpvntQIxswaGeE2wG1IDEzh1fl+694XLKvejFJzMzh1RZTwMhCdkZGj" +
"SJWVr5SnjEHT44o+MDjaPrt91gxyahRxMraYtpORoiCmpmyvesYMfcqCNvEKyNsnkVoq3ezLkx4qcW0e" +
"RahXTOl0C94eI9caGxiM0uTEzvVdGI6xHqZAzbJT4aQO8ADoUWJzQ0nqX/sfyuTjO7EpHa54SRVM1Ntw" +
"l+rbALf+zTmwDDKJtf7SqYZvwhs92nMATrOTFDbsY2F9gwrITdywVM0Vqbae0YmP7ZZVlMj05KiTXnoq" +
"jieRx7vFHAYIDJh28KxK5OJHAaIbDCFvsc5DO0sku3VMkqEvse5EuauIvF+gSgRqbbHrW7gSX4i2hn2u" +
"NUNPNliCi3LkA0nIV6NDPFCz2BYllExQ7waGeIFz2BSlmWUGLHtFUXy/o48TcOed3Umu62omI00DUVl5" +
"PdIwK+1t81UUm34vmYiAb8ZUzgS5eq+p4cnN7g5cCbyWqJsvO+J8GSDyXNc0+XYlr18RA5ZRt7/btjSn" +
"qsFwXE51mK68k3L/W+DqR8HRcAViFq5Xm1pGBP4wAyu751Crjs1z9ZM1wU1BLaYptsK4VktN9pRq0R9Y" +
"5/NMZL8slmC1ioSIu51ezNtkSACQ3HJckjXAX1v8nzsTxLwVBTT99OEiFxkMsNIVpu/J6yjhBpEG5mhv" +
"7vI8l+AAQB7WiwH/DuungAAAABJRU5ErkJggg==\"");

WriteAttribute("alt", Tuple.Create("\r\n                    alt=\"", 44003), Tuple.Create("\"", 44071)
            
            #line 191 "WelcomePage.cshtml"
, Tuple.Create(Tuple.Create("", 44030), Tuple.Create<System.Object, System.Int32>(Resources.WelcomePageImageText_LearnMore
            
            #line default
            #line hidden
, 44030), false)
);

WriteAttribute("title", Tuple.Create(" title=\"", 44072), Tuple.Create("\"", 44121)
            
            #line 191 "WelcomePage.cshtml"
, Tuple.Create(Tuple.Create("", 44080), Tuple.Create<System.Object, System.Int32>(Resources.WelcomePageImageText_LearnMore
            
            #line default
            #line hidden
, 44080), false)
);

WriteLiteral(" width=\"58\"");

WriteLiteral(" height=\"29\"");

WriteLiteral(" /></div>\r\n        </a>\r\n        <a");

WriteLiteral(" class=\"bodyCTA longer\"");

WriteLiteral(" href=\"http://go.microsoft.com/fwlink/?LinkID=313398&amp;clcid=0x409\"");

WriteLiteral(">");

            
            #line 193 "WelcomePage.cshtml"
                                                                                                  Write(Resources.WelcomeLearnMicrosoftOwin);

            
            #line default
            #line hidden
WriteLiteral("<div>\r\n            <img");

WriteLiteral(" src=\"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADoAAAAdCAYAAAD7En+mAAAAGXRFW" +
"HRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAyRpVFh0WE1MOmNvbS5hZG9iZS54bXAAAAAAA" +
"Dw/eHBhY2tldCBiZWdpbj0i77u/IiBpZD0iVzVNME1wQ2VoaUh6cmVTek5UY3prYzlkIj8+IDx4Onhtc" +
"G1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IkFkb2JlIFhNUCBDb3JlIDUuMy1jM" +
"DExIDY2LjE0NTY2MSwgMjAxMi8wMi8wNi0xNDo1NjoyNyAgICAgICAgIj4gPHJkZjpSREYgeG1sbnM6c" +
"mRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4gPHJkZjpEZXNjc" +
"mlwdGlvbiByZGY6YWJvdXQ9IiIgeG1sbnM6eG1wPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvI" +
"iB4bWxuczp4bXBNTT0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wL21tLyIgeG1sbnM6c3RSZWY9I" +
"mh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9zVHlwZS9SZXNvdXJjZVJlZiMiIHhtcDpDcmVhdG9yV" +
"G9vbD0iQWRvYmUgUGhvdG9zaG9wIENTNiAoTWFjaW50b3NoKSIgeG1wTU06SW5zdGFuY2VJRD0ieG1wL" +
"mlpZDozMjVCMDEwM0FBQkExMUUyQjdGNEEwODg0RjhFODY4OCIgeG1wTU06RG9jdW1lbnRJRD0ieG1wL" +
"mRpZDozMjVCMDEwNEFBQkExMUUyQjdGNEEwODg0RjhFODY4OCI+IDx4bXBNTTpEZXJpdmVkRnJvbSBzd" +
"FJlZjppbnN0YW5jZUlEPSJ4bXAuaWlkOjMyNUIwMTAxQUFCQTExRTJCN0Y0QTA4ODRGOEU4Njg4IiBzd" +
"FJlZjpkb2N1bWVudElEPSJ4bXAuZGlkOjMyNUIwMTAyQUFCQTExRTJCN0Y0QTA4ODRGOEU4Njg4Ii8+I" +
"DwvcmRmOkRlc2NyaXB0aW9uPiA8L3JkZjpSREY+IDwveDp4bXBtZXRhPiA8P3hwYWNrZXQgZW5kPSJyI" +
"j8+I1MZRAAAA4FJREFUeNq8md1x2kAQx3UaCoAKAg0YkgYQHTgV2KoAeMqjncfkBbsCSAd0AK5AOA1Y6" +
"YAOyJ7mf5rV6T4l8M3c2ALd/fZ/u/exh0gCy+VyyeiPrHPtqzPVd6p7IcTJ0rbxTO8FMe++/vIy/xY/T" +
"iF9CY+4If1ZUV1SHQb0V1L9Q/WFxJy7CCVxnZkk+hwtlIyTsCcGk53sMZJ8FGcY8Ux7NydB+xihJLI3k" +
"8Tug4TCi1uq92zEfpJxu4DwfoShY3y0o3a5Tyi82GKS0buA8G4xqV3uFAqRB4xYAoHPSURBH08IvwosR" +
"9omFCIbTDI0iok+GkxdrC5UjuqjHnpdCry7xaOcs2uLkQ2mLfQCBTeY1Ne6JRRzcoPH731EWsQuqM+jY" +
"U7WzD4iLWIX1GfFTLVwU+HaG4gQ3WExSRhcDzcVrldhYl63mAJCnwEtybiJx0tjNvETtCk9c/YDq2OuF" +
"jUSWjPJuInHSy0mtSk9c7ZmSvEpvntQIxswaGeE2wG1IDEzh1fl+694XLKvejFJzMzh1RZTwMhCdkZGj" +
"SJWVr5SnjEHT44o+MDjaPrt91gxyahRxMraYtpORoiCmpmyvesYMfcqCNvEKyNsnkVoq3ezLkx4qcW0e" +
"RahXTOl0C94eI9caGxiM0uTEzvVdGI6xHqZAzbJT4aQO8ADoUWJzQ0nqX/sfyuTjO7EpHa54SRVM1Ntw" +
"l+rbALf+zTmwDDKJtf7SqYZvwhs92nMATrOTFDbsY2F9gwrITdywVM0Vqbae0YmP7ZZVlMj05KiTXnoq" +
"jieRx7vFHAYIDJh28KxK5OJHAaIbDCFvsc5DO0sku3VMkqEvse5EuauIvF+gSgRqbbHrW7gSX4i2hn2u" +
"NUNPNliCi3LkA0nIV6NDPFCz2BYllExQ7waGeIFz2BSlmWUGLHtFUXy/o48TcOed3Umu62omI00DUVl5" +
"PdIwK+1t81UUm34vmYiAb8ZUzgS5eq+p4cnN7g5cCbyWqJsvO+J8GSDyXNc0+XYlr18RA5ZRt7/btjSn" +
"qsFwXE51mK68k3L/W+DqR8HRcAViFq5Xm1pGBP4wAyu751Crjs1z9ZM1wU1BLaYptsK4VktN9pRq0R9Y" +
"5/NMZL8slmC1ioSIu51ezNtkSACQ3HJckjXAX1v8nzsTxLwVBTT99OEiFxkMsNIVpu/J6yjhBpEG5mhv" +
"7vI8l+AAQB7WiwH/DuungAAAABJRU5ErkJggg==\"");

WriteAttribute("alt", Tuple.Create("\r\n                alt=\"", 46773), Tuple.Create("\"", 46837)
            
            #line 195 "WelcomePage.cshtml"
, Tuple.Create(Tuple.Create("", 46796), Tuple.Create<System.Object, System.Int32>(Resources.WelcomePageImageText_LearnMore
            
            #line default
            #line hidden
, 46796), false)
);

WriteAttribute("title", Tuple.Create(" title=\"", 46838), Tuple.Create("\"", 46887)
            
            #line 195 "WelcomePage.cshtml"
, Tuple.Create(Tuple.Create("", 46846), Tuple.Create<System.Object, System.Int32>(Resources.WelcomePageImageText_LearnMore
            
            #line default
            #line hidden
, 46846), false)
);

WriteLiteral(" width=\"58\"");

WriteLiteral(" height=\"29\"");

WriteLiteral(" /></div>\r\n        </a>\r\n    </div>\r\n\r\n</body>\r\n</html>\r\n");

        }
    }
}

