//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Owin.Host.SystemWeb {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Owin.Host.SystemWeb.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following errors occurred while attempting to load the app..
        /// </summary>
        internal static string Exception_AppLoderFailure {
            get {
                return ResourceManager.GetString("Exception_AppLoderFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot register for &apos;OnSendingHeaders&apos; event after response headers have been sent..
        /// </summary>
        internal static string Exception_CannotRegisterAfterHeadersSent {
            get {
                return ResourceManager.GetString("Exception_CannotRegisterAfterHeadersSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cookie key and options are larger than ChunksSize, leaving no room for data..
        /// </summary>
        internal static string Exception_CookieLimitTooSmall {
            get {
                return ResourceManager.GetString("Exception_CookieLimitTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key &apos;{0}&apos; is already present in the dictionary..
        /// </summary>
        internal static string Exception_DuplicateKey {
            get {
                return ResourceManager.GetString("Exception_DuplicateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To disable OWIN startup discovery, add the appSetting owin:AutomaticAppStartup with a value of &quot;false&quot; in your web.config..
        /// </summary>
        internal static string Exception_HowToDisableAutoAppStartup {
            get {
                return ResourceManager.GetString("Exception_HowToDisableAutoAppStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To specify the OWIN startup Assembly, Class, or Method, add the appSetting owin:AppStartup with the fully qualified startup class or configuration method name in your web.config..
        /// </summary>
        internal static string Exception_HowToSpecifyAppStartup {
            get {
                return ResourceManager.GetString("Exception_HowToSpecifyAppStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The chunked cookie is incomplete. Only {0} of the expected {1} chunks were found, totaling {2} characters. A client size limit may have been exceeded..
        /// </summary>
        internal static string Exception_ImcompleteChunkedCookie {
            get {
                return ResourceManager.GetString("Exception_ImcompleteChunkedCookie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given stage &apos;{0}&apos; is not supported..
        /// </summary>
        internal static string Exception_UnsupportedPipelineStage {
            get {
                return ResourceManager.GetString("Exception_UnsupportedPipelineStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No owin.Environment item was found in the context..
        /// </summary>
        internal static string HttpContext_OwinEnvironmentNotFound {
            get {
                return ResourceManager.GetString("HttpContext_OwinEnvironmentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception was thrown while trying to load the client certificate:.
        /// </summary>
        internal static string Trace_ClientCertException {
            get {
                return ResourceManager.GetString("Trace_ClientCertException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The OWIN entry point threw an exception:.
        /// </summary>
        internal static string Trace_EntryPointException {
            get {
                return ResourceManager.GetString("Trace_EntryPointException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The IAsyncResult callback for OwinCallHandler threw an exception:.
        /// </summary>
        internal static string Trace_OwinCallContextCallbackException {
            get {
                return ResourceManager.GetString("Trace_OwinCallContextCallbackException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to register the OWIN module:.
        /// </summary>
        internal static string Trace_RegisterModuleException {
            get {
                return ResourceManager.GetString("Trace_RegisterModuleException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application threw one or more exceptions when notified of a client disconnect:.
        /// </summary>
        internal static string Trace_RequestDisconnectCallbackExceptions {
            get {
                return ResourceManager.GetString("Trace_RequestDisconnectCallbackExceptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutdown detection setup failed:.
        /// </summary>
        internal static string Trace_ShutdownDetectionSetupException {
            get {
                return ResourceManager.GetString("Trace_ShutdownDetectionSetupException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more exceptions were thrown during app pool shutdown:.
        /// </summary>
        internal static string Trace_ShutdownException {
            get {
                return ResourceManager.GetString("Trace_ShutdownException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception was thrown from a timer callback:.
        /// </summary>
        internal static string Trace_TimerCallbackException {
            get {
                return ResourceManager.GetString("Trace_TimerCallbackException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception was thrown while processing the WebSocket:.
        /// </summary>
        internal static string Trace_WebSocketException {
            get {
                return ResourceManager.GetString("Trace_WebSocketException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support for WebSockets has been detected..
        /// </summary>
        internal static string Trace_WebSocketsSupportDetected {
            get {
                return ResourceManager.GetString("Trace_WebSocketsSupportDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No support for WebSockets has been detected..
        /// </summary>
        internal static string Trace_WebSocketsSupportNotDetected {
            get {
                return ResourceManager.GetString("Trace_WebSocketsSupportNotDetected", resourceCulture);
            }
        }
    }
}
