//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Owin.Host.SystemWeb {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Owin.Host.SystemWeb.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entering a blocking wait state is not allowed..
        /// </summary>
        internal static string Exception_BlockingNotAllowed {
            get {
                return ResourceManager.GetString("Exception_BlockingNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot register for event after headers are sent..
        /// </summary>
        internal static string Exception_CannotRegisterAfterHeadersSent {
            get {
                return ResourceManager.GetString("Exception_CannotRegisterAfterHeadersSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load the client certificate:.
        /// </summary>
        internal static string Exception_ClientCert {
            get {
                return ResourceManager.GetString("Exception_ClientCert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OwinHttpHandler cannot invoke a null app delegate..
        /// </summary>
        internal static string Exception_NullDelegate {
            get {
                return ResourceManager.GetString("Exception_NullDelegate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One more more exceptions were thrown on shutdown:.
        /// </summary>
        internal static string Exception_OnShutdown {
            get {
                return ResourceManager.GetString("Exception_OnShutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The IAsyncResult callback for OwinCallHandler threw an exception:.
        /// </summary>
        internal static string Exception_OwinCallContextCallbackThrew {
            get {
                return ResourceManager.GetString("Exception_OwinCallContextCallbackThrew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception was thrown while processing the WebSocket:.
        /// </summary>
        internal static string Exception_ProcessingWebSocket {
            get {
                return ResourceManager.GetString("Exception_ProcessingWebSocket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to register the OWIN module:.
        /// </summary>
        internal static string Exception_RegisterModule {
            get {
                return ResourceManager.GetString("Exception_RegisterModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request completed with an exception:.
        /// </summary>
        internal static string Exception_RequestComplete {
            get {
                return ResourceManager.GetString("Exception_RequestComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application threw one or more exceptions when notified of a client disconnect:.
        /// </summary>
        internal static string Exception_RequestDisconnect {
            get {
                return ResourceManager.GetString("Exception_RequestDisconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutdown detection setup failed:.
        /// </summary>
        internal static string Exception_ShutdownDetectionSetup {
            get {
                return ResourceManager.GetString("Exception_ShutdownDetectionSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception was thrown during module initialization startup:.
        /// </summary>
        internal static string Exception_Startup {
            get {
                return ResourceManager.GetString("Exception_Startup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception was thrown from a timer callback:.
        /// </summary>
        internal static string Exception_TimerCallback {
            get {
                return ResourceManager.GetString("Exception_TimerCallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support for WebSockets has been detected..
        /// </summary>
        internal static string WebSockets_SupportDetected {
            get {
                return ResourceManager.GetString("WebSockets_SupportDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No support for WebSockets has been detected..
        /// </summary>
        internal static string WebSockets_SupportNotDetected {
            get {
                return ResourceManager.GetString("WebSockets_SupportNotDetected", resourceCulture);
            }
        }
    }
}
